#  ⭐ `dim_duracao`

In [1]:
%run ../../config/bootstrap.py


from pathlib import Path
from utils import get_project_root , normalize_duracao

import re
import pandas as pd
from unidecode import unidecode

In [2]:
project_root = get_project_root()

# 🥉 Bronze 

Raw Data
as is production, low quality

In [3]:
path = Path(project_root) / "data/01_bronze/Medicamentos/Medicamentos.parquet"
bronze = pd.read_parquet(Path(project_root) / "data/01_bronze/Medicamentos/Medicamentos.parquet")  
bronze['DURACAO']= bronze['DURACAO'].fillna('DESCONHECIDO')
bronze = (
    bronze[['DURACAO']]
    .value_counts()
    .rename('FREQUENCIA_REGISTROS')
    .reset_index()
) 
bronze.columns

Index(['DURACAO', 'FREQUENCIA_REGISTROS'], dtype='object')

In [4]:
bronze.head()

        DURACAO  FREQUENCIA_REGISTROS
0  DESCONHECIDO                473049
1         1 dia                 20933
2         2 dia                  4107
3         3 dia                  3079
4        1 hora                  2959

In [5]:
bronze.DURACAO.nunique()

1538

In [6]:
bronze.to_csv(Path(project_root) / "data/01_bronze/Medicamentos/Medicamentos_DURACAO.csv", sep=";", index=False)

# 🥈 Silver

normalized data, medium quality

### dev

In [7]:
silver = bronze.copy()
 
silver.columns

Index(['DURACAO', 'FREQUENCIA_REGISTROS'], dtype='object')

In [8]:
silver.head(40)

         DURACAO  FREQUENCIA_REGISTROS
0   DESCONHECIDO                473049
1          1 dia                 20933
2          2 dia                  4107
3          3 dia                  3079
4         1 hora                  2959
5          5 dia                  2485
6       1 minuto                  2274
7          4 dia                  2253
8      30 minuto                  2101
9          7 dia                  1878
10        2 hora                  1577
11         6 dia                  1501
12         0 dia                  1404
13         8 dia                  1261
14        10 dia                  1105
15      5 minuto                  1070
16     10 minuto                  1058
17         9 dia                   843
18     20 minuto                   757
19        15 dia                   719
20     15 minuto                   718
21        11 dia                   709
22        3 hora                   693
23        14 dia                   651
24        12 dia                   577
25         1 ano                   576
26     60 minuto                   576
27        22 dia                   563
28         1 mês                   554
29         3 mês                   550
30         2 mês                   544
31        13 dia                   512
32        4 hora                   472
33     90 minuto                   439
34        21 dia                   378
35         2 ano                   374
36        16 dia                   373
37     40 minuto                   339
38         6 mês                   334
39       24 hora                   334

In [9]:
hist = normalize_duracao(bronze, coluna="DURACAO")

In [10]:
hist.head()

,DURACAO,FREQUENCIA_REGISTROS,DURACAO_TIPO_CHAVE,DURACAO_TIPO_VALOR,DURACAO_VALOR
0,DESCONHECIDO,473049,desconhecido,0,NaN
1,1 dia,20933,dia,4,1.0
2,2 dia,4107,dia,4,2.0
3,3 dia,3079,dia,4,3.0
4,1 hora,2959,hora,3,1.0

In [11]:
(
    hist[['DURACAO_TIPO_CHAVE', 'DURACAO_TIPO_VALOR']]
    .value_counts(dropna=False)
    .rename("count")
    .reset_index()
    .sort_values("DURACAO_TIPO_VALOR")
)

  DURACAO_TIPO_CHAVE  DURACAO_TIPO_VALOR  count
7       desconhecido                   0     18
5            segundo                   1     29
1             minuto                   2    215
2               hora                   3    116
0                dia                   4    984
6             semana                   5     28
3                mes                   6     85
4                ano                   7     63

In [11]:
hist[['DURACAO_VALOR']].value_counts(dropna=False)

DURACAO_VALOR
NaN              18
2.000            12
1.000            12
3.000            12
7.000            11
6.000            11
5.000            11
4.000            11
9.000            10
8.000            10
0.000            10
10.000            8
40.000            7
24.000            7
20.000            7
18.000            7
15.000            7
36.000            6
33.000            6
30.000            6
25.000            6
19.000            6
16.000            6
14.000            6
12.000            6
11.000            6
13.000            6
21.000            5
60.000            5
38.000            5
45.000            5
17.000            5
23.000            5
26.000            5
28.000            5
22.000            5
35.000            5
34.000            5
31.000            4
90.000            4
46.000            4
70.000            4
50.000            4
51.000            4
68.000            4
74.000            4
42.000            4
180.000           4
1.500             4
2.500             4
47.000            4
120.000           4
62.000            4
27.000            4
32.000            4
48.000            4
345.000           3
119.000           3
114.000           3
44.000            3
127.000           3
29.000            3
37.000            3
80.000            3
94.000            3
63.000            3
61.000            3
145.000           3
100.000           3
59.000            3
58.000            3
57.000            3
96.000            3
95.000            3
82.000            3
72.000            3
55.000            3
54.000            3
89.000            3
53.000            3
87.000            3
245.000           3
86.000            3
241.000           3
240.000           3
52.000            3
64.000            3
172.000           2
175.000           2
185.000           2
183.000           2
137.000           2
126.000           2
571.000           2
138.000           2
139.000           2
140.000           2
800.000           2
143.000           2
144.000           2
147.000           2
149.000           2
150.000           2
152.000           2
154.000           2
155.000           2
160.000           2
128.000           2
161.000           2
820.000           2
165.000           2
167.000           2
169.000           2
135.000           2
170.000           2
794.000           2
132.000           2
131.000           2
130.000           2
129.000           2
190.000           2
270.000           2
192.000           2
420.000           2
280.000           2
285.000           2
445.000           2
290.000           2
440.000           2
436.000           2
305.000           2
430.000           2
308.000           2
310.000           2
425.000           2
320.000           2
195.000           2
330.000           2
333.000           2
335.000           2
400.000           2
341.000           2
395.000           2
350.000           2
390.000           2
385.000           2
384.000           2
360.000           2
2021.000          2
273.000           2
2022.000          2
269.000           2
196.000           2
520.000           2
519.000           2
200.000           2
205.000           2
124.000           2
210.000           2
214.000           2
215.000           2
220.000           2
498.000           2
225.000           2
228.000           2
230.000           2
232.000           2
244.000           2
247.000           2
250.000           2
251.000           2
255.000           2
258.000           2
260.000           2
465.000           2
125.000           2
158.000           2
75.000            2
91.000            2
56.000            2
98.000            2
6.500             2
97.000            2
65.000            2
93.000            2
92.000            2
66.000            2
709.000           2
1.400             2
122.000           2
71.000            2
85.000            2
67.000            2
77.000            2
69.000            2
83.000            2
81.000            2
49.000            2
43.000            2
110.000           2
102.000           2
39.000            2
41.000            2
117.000           2
115.000           2
113.000           2
112.000           2
4.500             2
4.300             2
78.000            2
109.000           2
107.000           2
106.000           2
105.000           2
1.300             2
103.000           2
726.000           1
1058.000          1
1052.000          1
1063.000          1
725.000           1
1072.000          1
793.000           1
1092.000          1
1097.000          1
1105.000          1
724.000           1
1115.000          1
720.000           1
1117.000          1
718.000           1
722.000           1
1016.000          1
1041.000          1
1035.000          1
968.000           1
969.000           1
973.000           1
737.000           1
978.000           1
982.000           1
736.000           1
735.000           1
732.000           1
984.000           1
985.000           1
988.000           1
1002.000          1
1009.000          1
731.000           1
1011.000          1
1012.000          1
716.000           1
1026.000          1
730.000           1
1028.000          1
1031.000          1
728.000           1
727.000           1
1034.000          1
1121.000          1
1187.000          1
1125.000          1
1277.000          1
701.000           1
700.000           1
1295.000          1
1298.000          1
1308.000          1
699.000           1
697.000           1
1309.000          1
1314.000          1
1340.000          1
1341.000          1
695.000           1
1342.000          1
1343.000          1
1349.000          1
1350.000          1
1367.000          1
1369.000          1
1391.000          1
1398.000          1
1412.000          1
1293.000          1
702.000           1
1137.000          1
1270.000          1
1140.000          1
715.000           1
1146.000          1
1152.000          1
1184.000          1
1185.000          1
966.000           1
1188.000          1
1193.000          1
1196.000          1
1209.000          1
1217.000          1
708.000           1
1222.000          1
1223.000          1
707.000           1
1234.000          1
706.000           1
1235.000          1
703.000           1
1239.000          1
967.000           1
946.000           1
741.000           1
828.000           1
829.000           1
832.000           1
833.000           1
773.000           1
837.000           1
841.000           1
846.000           1
847.000           1
849.000           1
850.000           1
769.000           1
853.000           1
856.000           1
858.000           1
860.000           1
861.000           1
862.000           1
866.000           1
870.000           1
872.000           1
875.000           1
777.000           1
827.000           1
880.000           1
826.000           1
791.000           1
790.000           1
789.000           1
788.000           1
795.000           1
797.000           1
787.000           1
806.000           1
786.000           1
809.000           1
785.000           1
810.000           1
784.000           1
814.000           1
815.000           1
817.000           1
1420.000          1
818.000           1
781.000           1
780.000           1
824.000           1
879.000           1
881.000           1
965.000           1
924.000           1
934.000           1
938.000           1
942.000           1
944.000           1
754.000           1
753.000           1
945.000           1
750.000           1
749.000           1
947.000           1
748.000           1
948.000           1
949.000           1
746.000           1
743.000           1
950.000           1
953.000           1
960.000           1
961.000           1
964.000           1
742.000           1
932.000           1
918.000           1
882.000           1
755.000           1
883.000           1
885.000           1
886.000           1
887.000           1
896.000           1
897.000           1
768.000           1
763.000           1
904.000           1
905.000           1
906.000           1
910.000           1
760.000           1
911.000           1
759.000           1
913.000           1
757.000           1
914.000           1
916.000           1
756.000           1
917.000           1
1417.000          1
1.200             1
1435.000          1
3273.000          1
3286.000          1
3402.000          1
3403.000          1
3512.000          1
3567.000          1
3568.000          1
3591.000          1
3602.000          1
3652.000          1
3659.000          1
3711.000          1
3727.000          1
3745.000          1
3746.000          1
3753.000          1
3758.000          1
3800.000          1
3852.000          1
3926.000          1
4031.000          1
4135.000          1
4212.000          1
4289.000          1
3285.000          1
3271.000          1
4444.000          1
3219.000          1
2602.000          1
2617.000          1
2636.000          1
2671.000          1
2696.000          1
2709.000          1
2753.000          1
2757.000          1
2773.000          1
2814.000          1
2824.000          1
2837.000          1
2844.000          1
2850.000          1
2876.000          1
2880.000          1
2924.000          1
2952.000          1
2953.000          1
3000.000          1
3031.000          1
3043.000          1
3192.000          1
4323.000          1
4459.000          1
2579.000          1
6666.000          1
6723.000          1
7093.000          1
7305.000          1
7306.000          1
7365.000          1
7435.000          1
7459.000          1
7920.000          1
8087.000          1
8383.000          1
8514.000          1
8779.000          1
8802.000          1
8852.000          1
10292.000         1
10301.000         1
12960.000         1
15888.000         1
23548.000         1
30624.000         1
39391.000         1
47808.000         1
52075.000         1
6695.000          1
6534.000          1
4474.000          1
6000.000          1
4614.000          1
4616.000          1
4717.000          1
4804.000          1
4826.000          1
4858.000          1
4887.000          1
5035.000          1
5107.000          1
5293.000          1
5375.000          1
5424.000          1
5479.000          1
5503.000          1
5580.000          1
5661.000          1
5672.000          1
5679.000          1
5710.000          1
5729.000          1
5842.000          1
5844.000          1
5934.000          1
2586.000          1
2520.000          1
1436.000          1
1681.000          1
1697.000          1
1698.000          1
1705.000          1
1716.000          1
1730.000          1
1735.000          1
1739.000          1
1741.000          1
1742.000          1
1749.000          1
1756.000          1
1765.000          1
1766.000          1
1770.000          1
1784.000          1
1795.000          1
1802.000          1
1806.000          1
1807.000          1
1815.000          1
1824.000          1
1827.000          1
1850.000          1
1691.000          1
1678.000          1
1867.000          1
1656.000          1
1451.000          1
1488.000          1
1492.000          1
1511.000          1
1516.000          1
1523.000          1
1527.000          1
1532.000          1
1536.000          1
1551.000          1
1552.000          1
1557.000          1
1562.000          1
1567.000          1
1572.000          1
1575.000          1
1582.000          1
1586.000          1
1601.000          1
1612.000          1
1620.000          1
1626.000          1
1643.000          1
1856.000          1
1878.000          1
2501.000          1
2097.000          1
2109.000          1
2133.000          1
2153.000          1
2159.000          1
2182.000          1
2191.000          1
2192.000          1
2200.000          1
2226.000          1
2235.000          1
2278.000          1
2281.000          1
2300.000          1
2308.000          1
2360.000          1
2367.000          1
2373.000          1
2398.000          1
2413.000          1
2430.000          1
2444.000          1
2469.000          1
2489.000          1
2107.000          1
2092.000          1
1900.000          1
2080.000          1
1904.000          1
1916.000          1
1920.000          1
1923.000          1
1927.000          1
1928.000          1
1935.000          1
1939.000          1
1947.000          1
1956.000          1
1959.000          1
1976.000          1
1989.000          1
1991.000          1
2008.000          1
2019.000          1
2020.000          1
2024.000          1
692.000           1
2025.000          1
2045.000          1
2056.000          1
2059.000          1
694.000           1
513.000           1
689.000           1
361.000           1
256.000           1
257.000           1
259.000           1
261.000           1
264.000           1
265.000           1
266.000           1
267.000           1
268.000           1
271.000           1
272.000           1
274.000           1
275.000           1
276.000           1
277.000           1
278.000           1
279.000           1
281.000           1
282.000           1
283.000           1
284.000           1
286.000           1
287.000           1
254.000           1
253.000           1
252.000           1
231.000           1
213.000           1
216.000           1
217.000           1
218.000           1
219.000           1
221.000           1
222.000           1
223.000           1
226.000           1
229.000           1
233.000           1
249.000           1
234.000           1
235.000           1
236.000           1
237.000           1
238.000           1
239.000           1
242.000           1
243.000           1
246.000           1
248.000           1
288.000           1
291.000           1
292.000           1
343.000           1
326.000           1
329.000           1
331.000           1
332.000           1
334.000           1
336.000           1
337.000           1
338.000           1
339.000           1
342.000           1
344.000           1
324.000           1
346.000           1
347.000           1
349.000           1
351.000           1
352.000           1
353.000           1
355.000           1
356.000           1
357.000           1
358.000           1
325.000           1
323.000           1
293.000           1
307.000           1
294.000           1
295.000           1
296.000           1
297.000           1
298.000           1
300.000           1
302.000           1
303.000           1
304.000           1
306.000           1
309.000           1
322.000           1
311.000           1
312.000           1
313.000           1
314.000           1
315.000           1
316.000           1
317.000           1
318.000           1
319.000           1
321.000           1
212.000           1
211.000           1
209.000           1
5.500             1
4.250             1
4.400             1
4.470             1
4.600             1
4.730             1
4.800             1
4.825             1
0.500             1
5.250             1
5.300             1
0.300             1
3.900             1
0.200             1
0.167             1
0.100             1
9.800             1
10.250            1
73.000            1
76.000            1
79.000            1
84.000            1
88.000            1
1.110             1
3.800             1
101.000           1
2.300             1
1.417             1
1.450             1
1.490             1
1.700             1
1.800             1
1.900             1
1.167             1
2.118             1
2.170             1
2.200             1
2.450             1
3.750             1
2.526             1
2.700             1
2.750             1
2.786             1
1.150             1
3.200             1
3.250             1
3.400             1
3.500             1
3.700             1
99.000            1
104.000           1
208.000           1
191.000           1
177.000           1
178.000           1
179.000           1
181.000           1
182.000           1
184.000           1
186.000           1
187.000           1
188.000           1
189.000           1
193.000           1
174.000           1
194.000           1
197.000           1
198.000           1
199.000           1
201.000           1
202.000           1
203.000           1
204.000           1
206.000           1
207.000           1
176.000           1
173.000           1
108.000           1
146.000           1
111.000           1
116.000           1
118.000           1
121.000           1
123.000           1
133.000           1
134.000           1
136.000           1
141.000           1
142.000           1
148.000           1
171.000           1
151.000           1
153.000           1
156.000           1
157.000           1
159.000           1
162.000           1
163.000           1
164.000           1
166.000           1
168.000           1
359.000           1
362.000           1
688.000           1
364.000           1
558.000           1
559.000           1
560.000           1
564.000           1
565.000           1
567.000           1
568.000           1
569.000           1
573.000           1
574.000           1
577.000           1
578.000           1
579.000           1
580.000           1
581.000           1
584.000           1
585.000           1
586.000           1
587.000           1
588.000           1
589.000           1
590.000           1
593.000           1
550.000           1
549.000           1
547.000           1
525.000           1
0.083             1
508.000           1
509.000           1
510.000           1
511.000           1
512.000           1
1.250             1
514.000           1
515.000           1
517.000           1
526.000           1
545.000           1
527.000           1
528.000           1
529.000           1
530.000           1
531.000           1
535.000           1
538.000           1
539.000           1
540.000           1
542.000           1
595.000           1
597.000           1
598.000           1
669.000           1
643.000           1
644.000           1
647.000           1
648.000           1
649.000           1
653.000           1
658.000           1
660.000           1
663.000           1
666.000           1
670.000           1
641.000           1
672.000           1
673.000           1
675.000           1
676.000           1
677.000           1
679.000           1
680.000           1
681.000           1
684.000           1
685.000           1
642.000           1
640.000           1
600.000           1
618.000           1
603.000           1
604.000           1
605.000           1
606.000           1
608.000           1
609.000           1
610.000           1
611.000           1
612.000           1
616.000           1
619.000           1
638.000           1
622.000           1
623.000           1
624.000           1
626.000           1
627.000           1
628.000           1
629.000           1
630.000           1
632.000           1
637.000           1
505.000           1
504.000           1
503.000           1
413.000           1
398.000           1
399.000           1
401.000           1
402.000           1
403.000           1
405.000           1
406.000           1
409.000           1
410.000           1
411.000           1
415.000           1
396.000           1
416.000           1
417.000           1
418.000           1
419.000           1
422.000           1
423.000           1
424.000           1
426.000           1
427.000           1
429.000           1
397.000           1
394.000           1
433.000           1
377.000           1
365.000           1
366.000           1
367.000           1
368.000           1
369.000           1
370.000           1
371.000           1
372.000           1
374.000           1
375.000           1
378.000           1
393.000           1
379.000           1
380.000           1
381.000           1
382.000           1
383.000           1
386.000           1
387.000           1
388.000           1
389.000           1
391.000           1
431.000           1
434.000           1
502.000           1
487.000           1
475.000           1
476.000           1
478.000           1

In [12]:
hist.to_parquet(Path(project_root) / "data/02_silver/hist_dim_duracao/hist_dim_duracao.parquet", index=False)

# 🥇 Gold

In [13]:
hist.columns

Index(['DURACAO', 'FREQUENCIA_REGISTROS', 'DURACAO_TIPO_CHAVE',
       'DURACAO_TIPO_VALOR', 'DURACAO_VALOR'],
      dtype='object')

In [14]:
dim = hist[['DURACAO_TIPO_CHAVE', 'DURACAO_TIPO_VALOR']].drop_duplicates().sort_values('DURACAO_TIPO_VALOR')
dim

   DURACAO_TIPO_CHAVE  DURACAO_TIPO_VALOR
0        desconhecido                   0
75            segundo                   1
6              minuto                   2
4                hora                   3
1                 dia                   4
63             semana                   5
28                mes                   6
25                ano                   7

In [15]:
dim.to_parquet(Path(project_root) / "data/03_gold/dim_duracao/dim_duracao.parquet", index=False)