#  ⭐ `dim_indicacao_meddra`

In [7]:
%run ../../config/bootstrap.py


from pathlib import Path
from utils import get_project_root, fuzzy_merge, hungarian_text_link

import re
import pandas as pd
from unidecode import unidecode

In [8]:
project_root = get_project_root()

# 🥉 Bronze 

Raw Data
as is production, low quality

In [9]:
path = Path(project_root) / "data/01_bronze/anvisa/Medicamentos/Medicamentos.parquet"
bronze = pd.read_parquet(path)
bronze["INDICACAO_MEDDRA"] = bronze["INDICACAO_MEDDRA"].fillna("DESCONHECIDO")

bronze = pd.concat(
    [
        (
            bronze[["INDICACAO_MEDDRA"]]
            .value_counts()
            .rename("FREQUENCIA_REGISTROS")
            .reset_index()
        ),
        (
            bronze[["INDICACAO_RELATADA_NOTIFICADOR_INICIAL"]].rename(columns={"INDICACAO_RELATADA_NOTIFICADOR_INICIAL": "INDICACAO_MEDDRA"})
            .value_counts()
            .rename("FREQUENCIA_REGISTROS")
            .reset_index()
        ),
    ],
    ignore_index=True,
).drop_duplicates()

bronze.to_csv(
    Path(project_root) / "eda/Medicamentos/Medicamentos_INDICACAO_MEDDRA.csv",
    sep=";",
    index=False,
)

In [10]:
bronze.head()

                                 INDICACAO_MEDDRA  FREQUENCIA_REGISTROS
0                                    DESCONHECIDO                346290
1  Uso de medicamento para indicação desconhecida                 21287
2       Produto usado para indicação desconhecida                 18269
3                                 Doença de Crohn                  7328
4                              Artrite reumatoide                  6544

In [11]:
bronze.INDICACAO_MEDDRA.nunique()

71953

# 🥈 Silver

normalized data, medium quality

In [12]:
dim_soc_llt = pd.read_parquet(Path(project_root) / "data/03_gold/dim_soc_llt/dim_soc_llt.parquet") 
dim_soc_llt.head()

,SOC_CHAVE,SOC_VALOR,HLGT,HLT,PT,LLT_CHAVE,REACAO_EVTO_ADVERSO_MEDDRA_LLT_VALOR
0,26,Circunstâncias sociais,Fatores relacionados ao gênero,Circunstâncias relacionadas à gravidez,Amamentação,1,Amamentação
1,26,Circunstâncias sociais,Fatores relacionados ao gênero,Questões de sexualidade,Abstinência sexual,2,Abstinência sexual
2,26,Circunstâncias sociais,Fatores relacionados ao gênero,Questões de sexualidade,Atividade sexual aumentada,3,Atividade sexual aumentada
3,26,Circunstâncias sociais,Fatores relacionados ao gênero,Questões de sexualidade,Não consumação,4,Não consumação
4,26,Circunstâncias sociais,Fatores relacionados à idade,Questões relacionadas à idade,Bebê,5,Neonato

In [13]:
dim_soc_llt.shape

(18549, 7)

In [14]:
silver = pd.read_csv(Path(project_root) / "eda/Medicamentos/Medicamentos_INDICACAO_MEDDRA.csv", sep=";") ## Manual Normalization
 
silver.columns

Index(['INDICACAO_MEDDRA', 'FREQUENCIA_REGISTROS'], dtype='object')

In [15]:
silver.shape

(73804, 2)

In [16]:
hist_silver = fuzzy_merge(
    dim_df = dim_soc_llt[['PK_LLT', 'REACAO_EVTO_ADVERSO_MEDDRA_LLT']],
    fact_df = silver,
    dim_id_col="PK_LLT",
    dim_text_col="REACAO_EVTO_ADVERSO_MEDDRA_LLT",
    fact_text_col="INDICACAO_MEDDRA",
    threshold = 98)

KeyError: "None of [Index(['PK_LLT', 'REACAO_EVTO_ADVERSO_MEDDRA_LLT'], dtype='object')] are in the [columns]"

In [ ]:
hist_silver.shape

(69536, 5)

In [ ]:
hist_silver.PK_LLT_MATCH.value_counts(dropna=False)

PK_LLT_MATCH
NaN        60339
16588.0       23
16582.0       20
12629.0       18
7997.0        18
16753.0       18
7746.0        18
16273.0       17
12634.0       17
536.0         16
16292.0       16
16625.0       15
12197.0       14
7400.0        14
5362.0        14
2103.0        14
5693.0        14
17761.0       14
16950.0       14
7415.0        13
17766.0       13
16607.0       13
16833.0       13
5706.0        13
17100.0       12
16760.0       12
1209.0        12
7473.0        12
1575.0        12
10548.0       12
7735.0        12
4368.0        12
11289.0       12
11203.0       11
9704.0        11
12729.0       11
9169.0        11
5704.0        11
17798.0       11
16281.0       11
9635.0        10
1566.0        10
11765.0       10
229.0         10
11292.0       10
17942.0       10
143.0         10
1152.0         9
7742.0         9
7432.0         9
11888.0        9
5713.0         9
5924.0         9
9295.0         9
11519.0        9
5545.0         9
5269.0         9
5932.0         9
10680.0        9
16335.0        9
17920.0        9
5360.0         9
1278.0         9
1235.0         9
1212.0         9
1835.0         9
17932.0        9
16264.0        8
9721.0         8
5367.0         8
5523.0         8
11426.0        8
11579.0        8
16304.0        8
1640.0         8
16316.0        8
2939.0         8
12223.0        8
17784.0        8
16357.0        8
3146.0         8
17895.0        8
4840.0         8
18057.0        8
7806.0         8
16266.0        8
3908.0         8
1936.0         8
16566.0        7
5389.0         7
5405.0         7
16331.0        7
5227.0         7
1513.0         7
7995.0         7
17869.0        7
5354.0         7
10223.0        7
9742.0         7
18059.0        7
16819.0        7
16815.0        7
5274.0         7
8231.0         7
17767.0        7
17795.0        7
12641.0        7
3387.0         7
1199.0         7
16265.0        7
14613.0        7
495.0          7
17760.0        7
4372.0         7
9731.0         7
4442.0         7
13315.0        7
11483.0        7
14223.0        7
10887.0        7
18243.0        7
12979.0        7
8034.0         7
10736.0        7
10332.0        7
7401.0         7
6526.0         7
10212.0        7
1670.0         7
7564.0         7
18415.0        7
11904.0        7
6000.0         7
12736.0        7
7412.0         7
10262.0        7
3731.0         7
11877.0        7
12436.0        7
16743.0        7
9463.0         7
1325.0         7
12714.0        7
17052.0        7
654.0          7
5985.0         7
12122.0        7
3488.0         7
5519.0         7
8420.0         6
17591.0        6
4466.0         6
2708.0         6
2877.0         6
16274.0        6
1257.0         6
5255.0         6
1328.0         6
12779.0        6
12621.0        6
17770.0        6
853.0          6
11924.0        6
5967.0         6
17871.0        6
16560.0        6
9447.0         6
16752.0        6
2112.0         6
7500.0         6
5553.0         6
16280.0        6
16904.0        6
17870.0        6
12813.0        6
7671.0         6
6066.0         6
8032.0         6
9187.0         6
11729.0        6
7453.0         6
17143.0        6
12711.0        6
18118.0        6
13111.0        6
16755.0        6
16931.0        6
16521.0        6
10591.0        6
2779.0         6
11391.0        6
11818.0        6
8430.0         6
16444.0        6
3141.0         6
12498.0        6
12782.0        6
3692.0         6
7506.0         6
6481.0         6
9669.0         6
16333.0        6
10325.0        6
3002.0         6
10234.0        6
4460.0         6
17042.0        6
3139.0         6
690.0          6
358.0          6
11926.0        6
575.0          6
16744.0        6
10248.0        6
16939.0        6
10721.0        6
722.0          6
11298.0        6
12777.0        5
16246.0        5
2339.0         5
14603.0        5
1180.0         5
7462.0         5
4649.0         5
9462.0         5
11737.0        5
12434.0        5
16738.0        5
7198.0         5
12446.0        5
16847.0        5
12303.0        5
574.0          5
11969.0        5
11275.0        5
7521.0         5
10136.0        5
529.0          5
7804.0         5
12355.0        5
11624.0        5
12353.0        5
17050.0        5
11505.0        5
9647.0         5
17790.0        5
11710.0        5
8029.0         5
8802.0         5
226.0          5
1201.0         5
699.0          5
10025.0        5
12559.0        5
12642.0        5
9318.0         5
18055.0        5
10164.0        5
260.0          5
12429.0        5
1544.0         5
6394.0         5
370.0          5
5520.0         5
744.0          5
12721.0        5
10541.0        5
8253.0         5
11735.0        5
17975.0        5
16315.0        5
1525.0         5
7422.0         5
12487.0        5
11104.0        5
10.0           5
10129.0        5
7520.0         5
10112.0        5
9805.0         5
17048.0        5
17810.0        5
9968.0         5
12221.0        5
9452.0         5
5578.0         5
2938.0         5
3651.0         5
7676.0         5
7416.0         5
16622.0        5
9861.0         5
11807.0        5
9671.0         5
7348.0         5
9703.0         5
8211.0         5
7428.0         5
12332.0        5
7879.0         5
15472.0        5
16762.0        5
18195.0        5
11963.0        5
12720.0        5
9809.0         5
12326.0        5
3711.0         5
17089.0        5
11942.0        5
2538.0         5
4510.0         5
5641.0         5
8961.0         5
7439.0         5
9951.0         5
12665.0        5
10137.0        5
16342.0        5
7406.0         5
2536.0         5
1196.0         5
11987.0        5
17898.0        5
1283.0         5
10329.0        5
7867.0         5
10687.0        5
12747.0        5
11756.0        5
16735.0        5
1146.0         5
3504.0         5
12356.0        5
12546.0        5
10238.0        5
12918.0        5
15741.0        5
12324.0        5
1262.0         5
18427.0        5
17151.0        5
5927.0         5
8234.0         5
18056.0        5
12547.0        5
17746.0        5
3210.0         4
16873.0        4
17099.0        4
8415.0         4
7738.0         4
16842.0        4
11431.0        4
7817.0         4
16923.0        4
17090.0        4
16324.0        4
1857.0         4
17105.0        4
1335.0         4
16585.0        4
4186.0         4
12363.0        4
12139.0        4
485.0          4
14600.0        4
10796.0        4
14291.0        4
954.0          4
17534.0        4
4474.0         4
9865.0         4
15481.0        4
16801.0        4
18431.0        4
3418.0         4
12627.0        4
7470.0         4
11673.0        4
16806.0        4
11458.0        4
12137.0        4
12562.0        4
8255.0         4
2436.0         4
10233.0        4
9309.0         4
7558.0         4
10734.0        4
2203.0         4
5333.0         4
17141.0        4
12783.0        4
16528.0        4
11835.0        4
4505.0         4
2279.0         4
12485.0        4
11564.0        4
16371.0        4
4485.0         4
3708.0         4
7516.0         4
9640.0         4
11803.0        4
17044.0        4
5931.0         4
16288.0        4
10228.0        4
9464.0         4
7456.0         4
10739.0        4
10217.0        4
16023.0        4
5558.0         4
7882.0         4
3431.0         4
6547.0         4
12569.0        4
9228.0         4
9158.0         4
16940.0        4
10794.0        4
2510.0         4
16765.0        4
16865.0        4
13626.0        4
11511.0        4
17763.0        4
5640.0         4
4501.0         4
8246.0         4
540.0          4
2842.0         4
8196.0         4
9649.0         4
12719.0        4
16307.0        4
7824.0         4
7465.0         4
12992.0        4
7363.0         4
237.0          4
7996.0         4
5760.0         4
11338.0        4
16751.0        4
11421.0        4
1777.0         4
7488.0         4
5055.0         4
12160.0        4
2220.0         4
4122.0         4
12577.0        4
12778.0        4
5448.0         4
9442.0         4
7061.0         4
12504.0        4
6112.0         4
10352.0        4
12312.0        4
323.0          4
12110.0        4
3380.0         4
5486.0         4
2288.0         4
5777.0         4
5596.0         4
10350.0        4
2283.0         4
11742.0        4
12302.0        4
17056.0        4
7057.0         4
16980.0        4
7524.0         4
8036.0         4
1521.0         4
16577.0        4
12623.0        4
16906.0        4
16570.0        4
16569.0        4
16519.0        4
11734.0        4
16323.0        4
9605.0         4
11011.0        4
9287.0         4
5321.0         4
7992.0         4
2507.0         4
2353.0         4
17128.0        4
18205.0        4
8549.0         4
16703.0        4
16954.0        4
12407.0        4
11968.0        4
16848.0        4
12674.0        4
16254.0        4
17762.0        4
10098.0        4
3505.0         4
2425.0         4
11312.0        4
10741.0        4
9571.0         4
17006.0        4
5607.0         4
12739.0        4
1765.0         4
18058.0        4
11081.0        4
10287.0        4
5323.0         4
2261.0         4
8219.0         4
11007.0        4
855.0          4
11733.0        4
5601.0         4
10799.0        4
929.0          4
164.0          4
12444.0        4
18004.0        4
6126.0         4
17737.0        4
5129.0         4
7509.0         4
8132.0         4
9941.0         4
735.0          4
17098.0        4
16883.0        4
12600.0        4
16818.0        4
7108.0         4
8208.0         4
12315.0        4
4477.0         4
11643.0        4
258.0          4
11966.0        4
1551.0         4
16731.0        4
12465.0        4
12651.0        4
12046.0        4
3105.0         4
16785.0        4
7222.0         4
14151.0        4
9488.0         4
17083.0        4
11079.0        4
13077.0        4
11259.0        4
989.0          4
16618.0        3
16302.0        3
2222.0         3
5176.0         3
12991.0        3
17899.0        3
9651.0         3
11918.0        3
15462.0        3
252.0          3
3409.0         3
7966.0         3
18191.0        3
12387.0        3
11615.0        3
556.0          3
7411.0         3
5180.0         3
5561.0         3
2879.0         3
7431.0         3
16840.0        3
11922.0        3
541.0          3
16826.0        3
11582.0        3
7529.0         3
1150.0         3
12100.0        3
3419.0         3
3429.0         3
12914.0        3
18424.0        3
11318.0        3
17007.0        3
10246.0        3
18256.0        3
12742.0        3
10393.0        3
1839.0         3
12512.0        3
1642.0         3
476.0          3
7744.0         3
153.0          3
18495.0        3
8894.0         3
17812.0        3
11591.0        3
9668.0         3
462.0          3
18465.0        3
9616.0         3
8546.0         3
3152.0         3
5272.0         3
9814.0         3
2526.0         3
16028.0        3
8245.0         3
5962.0         3
16256.0        3
5635.0         3
15512.0        3
1586.0         3
16290.0        3
6131.0         3
16445.0        3
17037.0        3
16591.0        3
18240.0        3
16804.0        3
1518.0         3
1519.0         3
3140.0         3
17178.0        3
16632.0        3
16598.0        3
5275.0         3
11747.0        3
8054.0         3
4479.0         3
14159.0        3
10585.0        3
11677.0        3
3581.0         3
5963.0         3
9050.0         3
12472.0        3
7483.0         3
11015.0        3
8429.0         3
1774.0         3
11679.0        3
379.0          3
17104.0        3
2937.0         3
16737.0        3
4114.0         3
11212.0        3
10544.0        3
17161.0        3
5341.0         3
11331.0        3
10127.0        3
695.0          3
2338.0         3
18500.0        3
17085.0        3
188.0          3
6276.0         3
14203.0        3
7836.0         3
11077.0        3
11743.0        3
12438.0        3
13323.0        3
11767.0        3
16844.0        3
16642.0        3
10625.0        3
3716.0         3
8424.0         3
2539.0         3
9763.0         3
14202.0        3
17117.0        3
5418.0         3
1323.0         3
1837.0         3
147.0          3
5748.0         3
12481.0        3
16535.0        3
9928.0         3
7990.0         3
11341.0        3
11545.0        3
4445.0         3
4526.0         3
5727.0         3
10852.0        3
5132.0         3
181.0          3
12166.0        3
8157.0         3
1310.0         3
7862.0         3
7494.0         3
12062.0        3
11601.0        3
12475.0        3
1311.0         3
6447.0         3
1554.0         3
3203.0         3
11587.0        3
3048.0         3
3116.0         3
11755.0        3
12442.0        3
12647.0        3
7275.0         3
11724.0        3
18096.0        3
12304.0        3
6266.0         3
2725.0         3
11810.0        3
14584.0        3
3423.0         3
17181.0        3
9653.0         3
14153.0        3
17928.0        3
1227.0         3
4443.0         3
16984.0        3
6341.0         3
11821.0        3
4014.0         3
11752.0        3
17132.0        3
11875.0        3
7112.0         3
11840.0        3
7988.0         3
12347.0        3
8515.0         3
11869.0        3
7201.0         3
9465.0         3
9049.0         3
12633.0        3
9639.0         3
17940.0        3
12211.0        3
17910.0        3
3327.0         3
9830.0         3
17109.0        3
12734.0        3
7523.0         3
16825.0        3
16580.0        3
10229.0        3
726.0          3
16527.0        3
4129.0         3
16286.0        3
16776.0        3
1988.0         3
3458.0         3
16633.0        3
10226.0        3
17634.0        3
11267.0        3
817.0          3
11385.0        3
7982.0         3
1188.0         3
5233.0         3
11428.0        3
14371.0        3
11913.0        3
4707.0         3
7553.0         3
1659.0         3
15200.0        3
11006.0        3
3214.0         3
7224.0         3
12307.0        3
17088.0        3
10285.0        3
8442.0         3
16995.0        3
18091.0        3
16870.0        3
16623.0        3
10677.0        3
9660.0         3
3090.0         3
12566.0        3
14150.0        3
3671.0         3
7229.0         3
11625.0        3
7522.0         3
11741.0        3
10890.0        3
17772.0        3
16864.0        3
7472.0         3
18421.0        3
9765.0         3
4599.0         3
16347.0        3
5304.0         3
11970.0        3
2578.0         3
11796.0        3
3578.0         3
1637.0         3
12467.0        3
3966.0         3
4504.0         3
4911.0         3
11321.0        3
5358.0         3
12984.0        3
10222.0        3
5683.0         3
573.0          3
10553.0        3
8134.0         3
7294.0         3
5613.0         3
18162.0        3
5118.0         3
10746.0        3
10773.0        3
2989.0         3
9707.0         3
621.0          3
16658.0        3
14707.0        3
11612.0        3
4444.0         3
4469.0         3
5794.0         3
5611.0         3
17594.0        3
16341.0        3
12007.0        3
17929.0        3
14590.0        3
12239.0        3
1267.0         3
11859.0        3
6462.0         3
4859.0         3
13789.0        3
18494.0        3
11736.0        3
16358.0        3
148.0          3
5396.0         3
307.0          3
16531.0        3
7065.0         3
8082.0         3
3698.0         3
10221.0        3
12268.0        3
1009.0         3
18432.0        3
10991.0        3
3360.0         3
18053.0        3
10260.0        3
11809.0        3
16742.0        3
18017.0        3
9819.0         3
17892.0        3
12103.0        3
499.0          3
545.0          3
337.0          3
18143.0        3
4666.0         3
2249.0         3
9909.0         3
9599.0         3
3640.0         3
11122.0        3
1681.0         3
10275.0        3
11812.0        3
12503.0        3
17773.0        3
13633.0        3
17758.0        3
11097.0        3
12551.0        3
12769.0        3
18193.0        3
17939.0        3
10184.0        3
16314.0        3
7298.0         3
8252.0         3
5322.0         2
7888.0         2
1589.0         2
16602.0        2
16328.0        2
8363.0         2
2494.0         2
8055.0         2
2352.0         2
10012.0        2
5711.0         2
16480.0        2
9453.0         2
2547.0         2
187.0          2
16809.0        2
16592.0        2
12614.0        2
12333.0        2
11718.0        2
12637.0        2
11683.0        2
804.0          2
2943.0         2
3342.0         2
12588.0        2
18344.0        2
17636.0        2
12733.0        2
2681.0         2
11933.0        2
6369.0         2
11714.0        2
10156.0        2
14193.0        2
9383.0         2
12970.0        2
17753.0        2
12115.0        2
17782.0        2
5425.0         2
9813.0         2
13078.0        2
16447.0        2
7360.0         2
10646.0        2
12230.0        2
10215.0        2
633.0          2
6070.0         2
17771.0        2
12201.0        2
5550.0         2
12216.0        2
490.0          2
8811.0         2
17061.0        2
17956.0        2
12396.0        2
1107.0         2
11915.0        2
12437.0        2
10972.0        2
9748.0         2
7626.0         2
10803.0        2
6002.0         2
7144.0         2
5584.0         2
17970.0        2
5230.0         2
7803.0         2
10647.0        2
17842.0        2
2543.0         2
1840.0         2
10227.0        2
1644.0         2
11547.0        2
7230.0         2
7159.0         2
637.0          2
2123.0         2
11014.0        2
9953.0         2
18074.0        2
12522.0        2
15337.0        2
17010.0        2
253.0          2
2267.0         2
7550.0         2
4514.0         2
1197.0         2
11098.0        2
16769.0        2
17087.0        2
10186.0        2
7114.0         2
16036.0        2
4634.0         2
4398.0         2
4502.0         2
408.0          2
14161.0        2
6105.0         2
5388.0         2
10092.0        2
10717.0        2
18098.0        2
17949.0        2
9619.0         2
16787.0        2
10139.0        2
15127.0        2
5451.0         2
5152.0         2
7170.0         2
12820.0        2
3135.0         2
9883.0         2
620.0          2
9131.0         2
9080.0         2
16568.0        2
16758.0        2
13088.0        2
18034.0        2
9161.0         2
3371.0         2
16309.0        2
16861.0        2
13311.0        2
11237.0        2
3009.0         2
11990.0        2
12329.0        2
16970.0        2
691.0          2
14228.0        2
5605.0         2
1104.0         2
5880.0         2
3122.0         2
17149.0        2
3853.0         2
16326.0        2
3202.0         2
16172.0        2
16640.0        2
10172.0        2
10679.0        2
17860.0        2
4898.0         2
9925.0         2
15502.0        2
13091.0        2
5415.0         2
255.0          2
9256.0         2
175.0          2
8317.0         2
12295.0        2
13230.0        2
12129.0        2
11192.0        2
16802.0        2
11181.0        2
7486.0         2
17722.0        2
16322.0        2
11112.0        2
17897.0        2
12826.0        2
10299.0        2
7172.0         2
2118.0         2
13690.0        2
12913.0        2
11954.0        2
12266.0        2
11719.0        2
723.0          2
13608.0        2
3645.0         2
16793.0        2
12149.0        2
18242.0        2
3690.0         2
10035.0        2
11551.0        2
17076.0        2
9590.0         2
5402.0         2
2593.0         2
17131.0        2
12027.0        2
7414.0         2
11731.0        2
10001.0        2
16594.0        2
16794.0        2
7544.0         2
16955.0        2
12479.0        2
2868.0         2
2767.0         2
5254.0         2
9783.0         2
16476.0        2
8104.0         2
8202.0         2
4252.0         2
15169.0        2
12480.0        2
18018.0        2
5690.0         2
9240.0         2
1264.0         2
17538.0        2
9394.0         2
16790.0        2
16965.0        2
2952.0         2
3106.0         2
17081.0        2
16609.0        2
16533.0        2
1900.0         2
16576.0        2
16811.0        2
16974.0        2
7810.0         2
5617.0         2
9320.0         2
3150.0         2
11626.0        2
10644.0        2
1901.0         2
9443.0         2
11938.0        2
150.0          2
5546.0         2
16875.0        2
15457.0        2
9450.0         2
6035.0         2
16929.0        2
14364.0        2
12440.0        2
13646.0        2
16593.0        2
17805.0        2
16812.0        2
15143.0        2
1348.0         2

In [ ]:
hist_silver.head(10)

,INDICACAO_MEDDRA,FREQUENCIA_REGISTROS,INDICACAO_MEDDRA_SCORE,PK_LLT_MATCH,INDICACAO_MEDDRA_MATCH,PK_LLT
1,USO DE MEDICAMENTO PARA INDICAÇÃO DESCONHECIDA,19595,100.0,17870.0,USO DE MEDICAMENTO PARA INDICAÇÃO DESCONHECIDA,17870
2,PRODUTO USADO PARA INDICAÇÃO DESCONHECIDA,16515,100.0,17869.0,PRODUTO USADO PARA INDICAÇÃO DESCONHECIDA,17869
3,DOENÇA DE CROHN,6875,100.0,5362.0,DOENÇA DE CROHN,5362
4,ARTRITE REUMATOIDE,6207,100.0,7746.0,ARTRITE REUMATOIDE,7746
5,HIPERTENSÃO,4399,100.0,11289.0,HIPERTENSÃO,11289
7,ESCLEROSE MÚLTIPLA,4085,100.0,1575.0,ESCLEROSE MÚLTIPLA,1575
8,MIELOMA MÚLTIPLO,3449,100.0,16625.0,MIELOMA MÚLTIPLO,16625
9,ESPONDILITE ANQUILOSANTE,3139,100.0,7806.0,ESPONDILITE ANQUILOSANTE,7806
10,CÂNCER DE MAMA,3119,100.0,16582.0,CÂNCER DE MAMA,16582
11,DOR,2982,100.0,5924.0,DOR,5924

In [ ]:
dim_soc_llt.query("PK_LLT==5362")

,PK_SOC,SOC,HLGT,HLT,PT,PK_LLT,REACAO_EVTO_ADVERSO_MEDDRA_LLT
5361,14,Distúrbios gastrointestinais,Quadros clínicos gastrointestinais inflamatórios,Colite (excl. infecciosa),Doença de Crohn,5362,Doença de Crohn

In [ ]:
dim_soc_llt.query("PK_LLT==7746")

,PK_SOC,SOC,HLGT,HLT,PT,PK_LLT,REACAO_EVTO_ADVERSO_MEDDRA_LLT
7745,17,Distúrbios musculoesqueléticos e do tecido conjuntivo,Distúrbios articulares,Artropatias reumatoides,Artrite reumatoide,7746,Artrite reumatoide

In [ ]:
hist_silver.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69536 entries, 0 to 69535
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   INDICACAO_MEDDRA        69536 non-null  object
 1   FREQUENCIA_REGISTROS    69536 non-null  int64
 2   INDICACAO_MEDDRA_SCORE  69536 non-null  float64
 3   PK_LLT_MATCH            9197 non-null   float64
 4   INDICACAO_MEDDRA_MATCH  9197 non-null   object
dtypes: float64(2), int64(1), object(2)
memory usage: 2.7+ MB

In [ ]:
hist_silver = hist_silver.dropna(subset=["PK_LLT_MATCH"]).copy()
hist_silver["PK_LLT"] = hist_silver["PK_LLT_MATCH"].astype(int)

In [ ]:
hist_silver.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9197 entries, 1 to 69521
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   INDICACAO_MEDDRA        9197 non-null   object
 1   FREQUENCIA_REGISTROS    9197 non-null   int64
 2   INDICACAO_MEDDRA_SCORE  9197 non-null   float64
 3   PK_LLT_MATCH            9197 non-null   float64
 4   INDICACAO_MEDDRA_MATCH  9197 non-null   object
 5   PK_LLT                  9197 non-null   int64
dtypes: float64(2), int64(2), object(2)
memory usage: 503.0+ KB

In [ ]:
hist_silver.to_parquet(Path(project_root) / "data/02_silver/hist_indicacao_meddra/hist_indicacao_meddra.parquet", index=False)

# 🥇 Gold