#  ⭐ `dim_soc`

In [1]:
%run ../../config/bootstrap.py


from pathlib import Path
from utils import get_project_root , normalize_atc
 
import pandas as pd

In [2]:
project_root = get_project_root()

# 🥉 Bronze 

Raw Data
as is production, low quality

### ATC

In [3]:
bronze_atc = pd.read_excel(Path(project_root) / "data/01_bronze/atc/2025 ATC index with DDDs_english.xlsx")  
renomear = {
    "ATC code": "CODIGO_ATC_LEVEL",
    "ATC level name": "NIVEL_NOME_ATC",
    "DDD": "DDD_VALOR",
    "Unit": "DDD_UNIDADE",
    "Adm.R": "DDD_ADMINISTRACAO",
    "Comment": "DDD_COMENTARIO",
}

bronze_atc = bronze_atc.rename(columns=renomear)

In [4]:
bronze_atc.head(20)

,CODIGO_ATC_LEVEL,NIVEL_NOME_ATC,DDD_VALOR,DDD_UNIDADE,DDD_ADMINISTRACAO,DDD_COMENTARIO
0,A,ALIMENTARY TRACT AND METABOLISM,NaN,NaN,NaN,NaN
1,A01,STOMATOLOGICAL PREPARATIONS,NaN,NaN,NaN,NaN
2,A01AA,Caries prophylactic agents,NaN,NaN,NaN,NaN
3,A01AA01,sodium fluoride,1.10,mg,O,0.5 mg fluoride
4,A01AA02,sodium monofluorophosphate,NaN,NaN,NaN,NaN
5,A01AA03,olaflur,1.10,mg,O,NaN
6,A01AA04,stannous fluoride,NaN,NaN,NaN,NaN
7,A01AA30,combinations,NaN,NaN,NaN,NaN
8,A01AA51,"sodium fluoride, combinations",NaN,NaN,NaN,NaN
9,A01A,STOMATOLOGICAL PREPARATIONS,NaN,NaN,NaN,NaN
10,A01AB,Antiinfectives and antiseptics for local oral treatment,NaN,NaN,NaN,NaN
11,A01AB02,hydrogen peroxide,60.00,mg,O,NaN
12,A01AB03,chlorhexidine,30.00,mg,O,NaN
13,A01AB04,amphotericin B,40.00,mg,O,NaN
14,A01AB05,polynoxylin,0.18,g,O,NaN
15,A01AB06,domiphen,3.00,mg,O,NaN
16,A01AB07,oxyquinoline,80.00,mg,O,NaN
17,A01AB08,neomycin,NaN,NaN,NaN,NaN
18,A01AB09,miconazole,0.20,g,O,NaN
19,A01AB10,natamycin,20.00,mg,O,NaN

In [5]:
bronze_atc[bronze_atc["NIVEL_NOME_ATC"].str.contains("oxyquinoline", case=False, na=False)].head(20)

,CODIGO_ATC_LEVEL,NIVEL_NOME_ATC,DDD_VALOR,DDD_UNIDADE,DDD_ADMINISTRACAO,DDD_COMENTARIO
16,A01AB07,oxyquinoline,80.0,mg,O,NaN
465,A07AX01,broxyquinoline,NaN,NaN,NaN,NaN
2483,D08AH03,oxyquinoline,NaN,NaN,NaN,NaN
2656,G01AC01,diiodohydroxyquinoline,0.2,g,V,NaN
2660,G01AC06,broxyquinoline,0.1,g,V,NaN
2661,G01AC30,oxyquinoline,NaN,NaN,NaN,NaN
5898,P01AA,Hydroxyquinoline derivatives,NaN,NaN,NaN,NaN
5899,P01AA01,broxyquinoline,NaN,NaN,NaN,NaN
6175,R02AA14,oxyquinoline,NaN,NaN,NaN,NaN

In [6]:
bronze_atc.columns

Index(['CODIGO_ATC_LEVEL', 'NIVEL_NOME_ATC', 'DDD_VALOR', 'DDD_UNIDADE',
       'DDD_ADMINISTRACAO', 'DDD_COMENTARIO'],
      dtype='object')

In [7]:
bronze_atc[['CODIGO_ATC_LEVEL', 'NIVEL_NOME_ATC']].describe()

       CODIGO_ATC_LEVEL NIVEL_NOME_ATC
count              7435           7435
unique             6897           6045
top             G03CA03   combinations
freq                 10             38

### MEDICAMENTOS

In [8]:
 
bronze = pd.read_parquet(Path(project_root) / "data/01_bronze/Medicamentos/Medicamentos.parquet") 
bronze = bronze[['NOME_MEDICAMENTO_WHODRUG', 'PRINCIPIOS_ATIVOS_WHODRUG', 'CODIGO_ATC']].drop_duplicates()
bronze.head(20)

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC
0,Oxacilina,Oxacillin sodium,J01CF
1,Paracemol,Paracetamol,N02BE
2,Diamox,Acetazolamide sodium,C03|N03AX|S01EC
3,Hidantal,Phenytoin,N03AB
4,Nitroglicerina,Glyceryl trinitrate,C01DA|C05AE
5,Macrodantina,Nitrofurantoin,J01XE
6,Dexa-Citoneurin,Cyanocobalamin|Dexamethasone|Pyridoxine hydrochloride|Thiamine hydrochloride,H02BX
7,Benzetacil,Benzathine benzylpenicillin,J01CE
8,Reuquinol,Hydroxychloroquine sulfate,P01BA
9,Anfotericina b,Amphotericin b,J02AA
10,Oxaliplatina,Oxaliplatin,L01XA
11,Dimorf,Morphine sulfate,N02AA
16,Gynera,Ethinylestradiol|Gestodene,G03AA
17,Hetori,Etoricoxib,M01AH
18,Genuxal,Cyclophosphamide,L01AA
19,Dipirona,Metamizole sodium,N02BB
20,Docelibbs,Docetaxel,L01CD
21,Cetoprofeno,Ketoprofen,M01AE|M02AA
22,Gentamicin,Gentamicin,D06AX|J01GB|S01AA|S02AA|S03AA
23,Ondansetron,Ondansetron,A04AA

In [9]:
bronze.describe()

       NOME_MEDICAMENTO_WHODRUG PRINCIPIOS_ATIVOS_WHODRUG CODIGO_ATC
count                     20224                     20124      20224
unique                    12490                      6501       2315
top                     Calcium            Colecalciferol      J01CR
freq                         19                        60        315

In [10]:
bronze[bronze["NOME_MEDICAMENTO_WHODRUG"].str.contains("oxyquinoline", case=False, na=False)].head(20)

Empty DataFrame
Columns: [NOME_MEDICAMENTO_WHODRUG, PRINCIPIOS_ATIVOS_WHODRUG, CODIGO_ATC]
Index: []

In [11]:
bronze[bronze["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("oxyquinoline", case=False, na=False)].head(20)

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC
28579,Cerumin,Hydroxyquinoline borate|Trolamine,S02DC
251441,Malvatricin,Hydroxyquinoline sulfate|Tyrothricin,A01AB|R02AB
300362,Malvatricin,Hydroxyquinoline sulfate|Lidocaine hydrochloride|Tyrothricin,A01AD|R02AX
331509,Cerumin,Hydroxyquinoline borate_x000D_|Trolamine,S02DC

# 🥈 Silver

normalized data, medium quality

In [12]:
silver = bronze.copy()

In [13]:
hist = normalize_atc(silver, bronze_atc, threshold=75)
hist.head()

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,CODIGO_ATC_LEVEL,CODIGO_ATC_LEVEL_SCORE
0,Oxacilina,Oxacillin sodium,J01CF,J01CF04,76.923077
1,Paracemol,Paracetamol,N02BE,N02BE01,94.444444
2,Diamox,Acetazolamide sodium,C03|N03AX|S01EC,S01EC01,76.470588
3,Hidantal,Phenytoin,N03AB,N03AB02,93.750000
4,Nitroglicerina,Glyceryl trinitrate,C01DA|C05AE,C01DA02,89.655172

In [14]:
hist[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("oxyquinoline", case=False, na=False)].head(20)

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,CODIGO_ATC_LEVEL,CODIGO_ATC_LEVEL_SCORE
28579,Cerumin,Hydroxyquinoline borate|Trolamine,S02DC,desconhecido,NaN
251441,Malvatricin,Hydroxyquinoline sulfate|Tyrothricin,A01AB|R02AB,desconhecido,NaN
300362,Malvatricin,Hydroxyquinoline sulfate|Lidocaine hydrochloride|Tyrothricin,A01AD|R02AX,desconhecido,NaN
331509,Cerumin,Hydroxyquinoline borate_x000D_|Trolamine,S02DC,desconhecido,NaN

In [15]:
hist[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("rituximab", case=False, na=False)].head(40)

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,CODIGO_ATC_LEVEL,CODIGO_ATC_LEVEL_SCORE
91,Mabthera,Rituximab,L01XC,L01FA01,81.250000
350,Rituximab,Rituximab,L01XC,L01FA01,81.250000
10953,Mabthera sc,Rituximab,L01XC,L01FA01,81.250000
13289,Vivaxxia,Rituximab,L01XC,L01FA01,81.250000
27060,Riximyo,Rituximab,L01XC,L01FA01,81.250000
53211,R CHOP,Cyclophosphamide|Doxorubicin hydrochloride|Prednisone|Rituximab|Vincristine sulfate,L01XY,desconhecido,NaN
65137,Ruxience,Rituximab,L01XC,L01FA01,81.250000
75255,Rituxan,Rituximab,L01XC,L01FA01,81.250000
75363,Truxima,Rituximab,L01XC,L01FA01,81.250000
93432,Truxima,Rituximab abbs,L01XC,L01FA01,81.250000
160665,Rituximab,Rituximab,L01FA,L01FA01,93.750000
160758,Riximyo,Rituximab,L01FA,L01FA01,93.750000
161321,Vivaxxia,Rituximab,L01FA,L01FA01,93.750000
163456,Mabthera,Rituximab,L01FA,L01FA01,93.750000
167056,Truxima,Rituximab,L01FA,L01FA01,93.750000
167263,Rituximab bs,Rituximab biosimilar 2,L01FA,L01FA01,93.750000
186706,Ruxience,Rituximab pvvr,L01FA,L01FA01,93.750000
188742,Mabthera sc,Rituximab,L01FA,L01FA01,93.750000
193435,Truxima,Rituximab abbs,L01FA,L01FA01,93.750000
194835,Mabthera,Rituximabe,L01FA,L01FA01,90.909091
222229,Rituximab abbs,Rituximab abbs,L01FA,L01FA01,93.750000
250616,Rituxan,Rituximab,L01FA,L01FA01,93.750000
284326,Rituximabum,Rituximab,L01FA,L01FA01,93.750000
302506,R CVP,Cyclophosphamide|Prednisone|Rituximab|Vincristine sulfate,L01XY,desconhecido,NaN
307879,Truxima,Rituximabe,L01FA_x000D_|L04AG,L01FA01,82.051282
308348,Rituximab,Rituximabe,L01FA_x000D_|L04AG,L01FA01,82.051282
308456,Tuximab,Rituximabe,L01FA,L01FA01,90.909091
309392,Vivaxxia,Rituximabe,L01FA,L01FA01,90.909091
309906,Riximyo,Rituximabe,L01FA,L01FA01,90.909091
317190,Ruxience,Rituximabe,L01FA,L01FA01,90.909091
319831,Mabthera sc,Rituximabe,L01FA,L01FA01,90.909091
332525,R CHOP,Ciclofosfamida_x000D_|Cloridrato de doxorrubicina_x000D_|Prednisone_x000D_|Rituximabe_x000D_|Sulfato de vincristina,L01XY,desconhecido,NaN
340927,Rixathon,Rituximabe,L01FA,L01FA01,90.909091
374833,"Rituximab,Venetoclax",Rituximabe_x000D_|Venetoclax,L01XY,desconhecido,NaN
377999,Rituximab bs pfizer,Rituximab biosimilar 2,L01FA,L01FA01,93.750000
379371,Rituxim,Rituximabe,L01FA,L01FA01,90.909091
380311,Truxima,Rituximabe,L01FA,L01FA01,90.909091
385907,"Cyclophosphamide,Prednisone,Rituximab,Vincristine sulfate",Ciclofosfamida_x000D_|Prednisone_x000D_|Rituximabe_x000D_|Sulfato de vincristina,L01XY,desconhecido,NaN
418745,"Cyclophosphamide,Prednisone,Rituximab",Ciclofosfamida_x000D_|Prednisone_x000D_|Rituximabe,L01XY,desconhecido,NaN
421035,Rituximab bs,Rituximab biosimilar 1,L01FA,L01FA01,93.750000

In [16]:
hist.query("CODIGO_ATC_LEVEL=='desconhecido'")[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("rituximab", case=False, na=False)].head(40).sort_values(by="CODIGO_ATC")

/var/folders/6r/t8g0l_4n2h97mg8j0fp43scr0000gn/T/ipykernel_71057/2012540531.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  hist.query("CODIGO_ATC_LEVEL=='desconhecido'")[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("rituximab", case=False, na=False)].head(40).sort_values(by="CODIGO_ATC")

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,CODIGO_ATC_LEVEL,CODIGO_ATC_LEVEL_SCORE
53211,R CHOP,Cyclophosphamide|Doxorubicin hydrochloride|Prednisone|Rituximab|Vincristine sulfate,L01XY,desconhecido,NaN
302506,R CVP,Cyclophosphamide|Prednisone|Rituximab|Vincristine sulfate,L01XY,desconhecido,NaN
332525,R CHOP,Ciclofosfamida_x000D_|Cloridrato de doxorrubicina_x000D_|Prednisone_x000D_|Rituximabe_x000D_|Sulfato de vincristina,L01XY,desconhecido,NaN
374833,"Rituximab,Venetoclax",Rituximabe_x000D_|Venetoclax,L01XY,desconhecido,NaN
385907,"Cyclophosphamide,Prednisone,Rituximab,Vincristine sulfate",Ciclofosfamida_x000D_|Prednisone_x000D_|Rituximabe_x000D_|Sulfato de vincristina,L01XY,desconhecido,NaN
418745,"Cyclophosphamide,Prednisone,Rituximab",Ciclofosfamida_x000D_|Prednisone_x000D_|Rituximabe,L01XY,desconhecido,NaN
467230,"Chlorambucil,Rituximab",Clorambucila_x000D_|Rituximabe,L01XY,desconhecido,NaN
476476,R GEMOX,Gencitabina_x000D_|Oxaliplatina_x000D_|Rituximabe,L01XY,desconhecido,NaN
509527,FCR,Ciclofosfamida_x000D_|Fludarabine_x000D_|Rituximabe,L01XY,desconhecido,NaN
541317,"Rituximab,Venetoclax",Rituximabe|Venetoclax,L01XY,desconhecido,NaN

In [17]:
hist.query("CODIGO_ATC_LEVEL=='desconhecido'")[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("ertolizumab", case=False, na=False)].head(40).sort_values(by="CODIGO_ATC")

/var/folders/6r/t8g0l_4n2h97mg8j0fp43scr0000gn/T/ipykernel_71057/2000822013.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  hist.query("CODIGO_ATC_LEVEL=='desconhecido'")[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("ertolizumab", case=False, na=False)].head(40).sort_values(by="CODIGO_ATC")

Empty DataFrame
Columns: [NOME_MEDICAMENTO_WHODRUG, PRINCIPIOS_ATIVOS_WHODRUG, CODIGO_ATC, CODIGO_ATC_LEVEL, CODIGO_ATC_LEVEL_SCORE]
Index: []

In [18]:
histv2 = hist.query("CODIGO_ATC_LEVEL=='desconhecido'")[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("ertolizumab", case=False, na=False)].head(40).sort_values(by="CODIGO_ATC")
histv2 = normalize_atc(histv2, bronze_atc, threshold=75)
histv2.head()

/var/folders/6r/t8g0l_4n2h97mg8j0fp43scr0000gn/T/ipykernel_71057/3878801764.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  histv2 = hist.query("CODIGO_ATC_LEVEL=='desconhecido'")[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("ertolizumab", case=False, na=False)].head(40).sort_values(by="CODIGO_ATC")

Empty DataFrame
Columns: [NOME_MEDICAMENTO_WHODRUG, PRINCIPIOS_ATIVOS_WHODRUG, CODIGO_ATC, CODIGO_ATC_LEVEL, CODIGO_ATC_LEVEL_SCORE]
Index: []

In [19]:
hist[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("golimumab", case=False, na=False)].head(20)

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,CODIGO_ATC_LEVEL,CODIGO_ATC_LEVEL_SCORE
1651,Simponi,Golimumab,L04AB,L04AB06,93.750000
10798,Golimumab,Golimumab,L04AB,L04AB06,93.750000
267667,Simponi aria,Golimumab,L04AB,L04AB06,93.750000
307771,Simponi,Golimumabe,L04AB,L04AB06,90.909091
308109,Golimumab,Golimumabe,L04AB,L04AB06,90.909091
320610,Bio manguinhos golimumabe,Golimumabe,L04AB,L04AB06,90.909091
412527,Golimumab recombinant,Golimumabe,L04AB,L04AB06,90.909091
445904,Simponi iv,Golimumabe,L04AB,L04AB06,90.909091

In [20]:
hist[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("infliximab", case=False, na=False)].head(20)

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,CODIGO_ATC_LEVEL,CODIGO_ATC_LEVEL_SCORE
152,Remicade,Infliximab,L04AB,L04AB02,94.117647
164,Bio manguinhos infliximabe,Infliximab,L04AB,L04AB02,94.117647
859,Infliximab,Infliximab,L04AB,L04AB02,94.117647
5437,Remsima,Infliximab,L04AB,L04AB02,94.117647
34679,Infliximab bs pfizer,Infliximab biosimilar 3,L04AB,L04AB02,94.117647
53570,Remicade lyophilisat,Infliximab,L04AB,L04AB02,94.117647
88179,Infliximab Recombinant,Infliximab,L04AB,L04AB02,94.117647
96237,Infliximab dyyb,Infliximab dyyb,L04AB,L04AB02,82.051282
103939,Infliximab bs nichiiko,Infliximab,L04AB,L04AB02,94.117647
151373,Xilfya,Infliximab,L04AB,L04AB02,94.117647
215557,Infliximab biosimilar 1,Infliximab biosimilar 1,L04AB,L04AB02,94.117647
302016,Avsola,Infliximab,L04AB,L04AB02,94.117647
307778,Infliximab,Infliximabe,L04AB,L04AB02,91.428571
307779,Remicade,Infliximabe,L04AB,L04AB02,91.428571
308183,Remsima,Infliximabe,L04AB,L04AB02,91.428571
308549,Bio manguinhos infliximabe,Infliximabe,L04AB,L04AB02,91.428571
309184,Xilfya,Infliximabe,L04AB,L04AB02,91.428571
309545,Infliximab Recombinant,Infliximabe,L04AB,L04AB02,91.428571
315167,Avsola,Infliximabe,L04AB,L04AB02,91.428571
403322,Infliximabum,Infliximabe,L04AB,L04AB02,91.428571

In [26]:
hist.to_csv(
    Path(project_root) / "data/02_silver/hist_dim_atc/hist_dim_atc_MANUAL.csv",
    sep=";",
    decimal=",",
    encoding="utf-8-sig",   # em vez de utf-8
    index=False,
)

In [22]:
silver.head(2)

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,CODIGO_ATC_LEVEL,CODIGO_ATC_LEVEL_SCORE
0,Oxacilina,Oxacillin sodium,J01CF,J01CF04,76.923077
1,Paracemol,Paracetamol,N02BE,N02BE01,94.444444

# 🥇 Gold

In [23]:
hist.columns

Index(['NOME_MEDICAMENTO_WHODRUG', 'PRINCIPIOS_ATIVOS_WHODRUG', 'CODIGO_ATC',
       'CODIGO_ATC_LEVEL', 'CODIGO_ATC_LEVEL_SCORE'],
      dtype='object')

In [24]:
#dim = hist[['DETENTOR_REGISTRO_CHAVE', 'DETENTOR_REGISTRO_VALOR']].drop_duplicates()
#dim.to_parquet(Path(project_root) / "data/03_gold/dim_detentor_registro/dim_detentor_registro.parquet", index=False)

In [25]:

#dim.to_csv(Path(project_root) / "data/03_gold/dim_detentor_registro/dim_detentor_registro.csv", sep=";", index=False)