#  ⭐ `dim_detentor_registro`

In [2]:
%run ../../config/bootstrap.py


from pathlib import Path
from utils import get_project_root,add_key_value_columns,fuzzy_merge
import pandas as pd
project_root = get_project_root()

# 🥉 Bronze 

Raw Data
as is production, low quality

In [3]:
path = Path(project_root) / "data/01_bronze/anvisa/Medicamentos/Medicamentos.parquet"
bronze = pd.read_parquet(Path(project_root) / "data/01_bronze/anvisa/Medicamentos/Medicamentos.parquet")  
bronze['DETENTOR_REGISTRO']= bronze['DETENTOR_REGISTRO'].fillna('DESCONHECIDO')
bronze = (
    bronze[['DETENTOR_REGISTRO']]
    .value_counts()
    .rename('FREQUENCIA_REGISTROS')
    .reset_index()
) 
bronze.columns

Index(['DETENTOR_REGISTRO', 'FREQUENCIA_REGISTROS'], dtype='object')

In [4]:
bronze.shape

(10940, 2)

In [5]:
bronze.DETENTOR_REGISTRO.nunique()

10940

In [6]:
bronze.to_csv(Path(project_root) / "eda/Medicamentos/Medicamentos_DETENTOR_REGISTRO.csv", sep=";", index=False)

# 🥈 Silver

normalized data, medium quality

### canonical

In [7]:
silver = pd.read_excel(Path(project_root) /  "data/02_silver/hist_dim_detentor_registro/hist_dim_detentor_registro_MANUAL.xlsx")
silver = silver.drop_duplicates(subset=['DETENTOR_REGISTRO'])
silver.head()

                DETENTOR_REGISTRO DETENTOR_REGISTRO_PADRONIZADO
0                 ABACUS MEDICINE               ABACUS MEDICINE
1                          ABBOLT                         ABBOT
2                           ABBOT                         ABBOT
3                    ABBOT BRASIL                         ABBOT
4  ABBOT L: 0071/20 V: 31/01/2022                         ABBOT

In [8]:
silver.shape

(4078, 2)

In [9]:
silver.DETENTOR_REGISTRO.value_counts().head(10)

DETENTOR_REGISTRO

In [10]:
silver.query("DETENTOR_REGISTRO == 'BIONTECH - PFIZER'")

      DETENTOR_REGISTRO DETENTOR_REGISTRO_PADRONIZADO
3590  BIONTECH - PFIZER                        PFIZER

In [11]:
hist = add_key_value_columns(
    silver, #.query("DETENTOR_REGISTRO_PADRONIZADO != 'DESCONHECIDO'"),
    base_col="DETENTOR_REGISTRO",
    normalized_col="DETENTOR_REGISTRO_PADRONIZADO",
)

hist.head()

,DETENTOR_REGISTRO,DETENTOR_REGISTRO_PADRONIZADO,DETENTOR_REGISTRO_VALOR,DETENTOR_REGISTRO_CHAVE
0,ABACUS MEDICINE,ABACUS MEDICINE,ABACUS MEDICINE,1
1,ABBOLT,ABBOT,ABBOT,2
2,ABBOT,ABBOT,ABBOT,2
3,ABBOT BRASIL,ABBOT,ABBOT,2
4,ABBOT L: 0071/20 V: 31/01/2022,ABBOT,ABBOT,2

In [12]:
hist.to_parquet(Path(project_root) / "data/02_silver/hist_dim_detentor_registro/hist_dim_detentor_registro.parquet", index=False)

# 🥇 Gold

In [13]:
hist.columns

Index(['DETENTOR_REGISTRO', 'DETENTOR_REGISTRO_PADRONIZADO',
       'DETENTOR_REGISTRO_VALOR', 'DETENTOR_REGISTRO_CHAVE'],
      dtype='object')

In [14]:
dim = hist[['DETENTOR_REGISTRO_CHAVE', 'DETENTOR_REGISTRO_VALOR']].drop_duplicates()

In [15]:

dim.to_csv(Path(project_root) / "data/03_gold/dim_detentor_registro/dim_detentor_registro.csv", sep=";", index=False)

In [16]:
dim

,DETENTOR_REGISTRO_CHAVE,DETENTOR_REGISTRO_VALOR
0,1,ABACUS MEDICINE
1,2,ABBOT
30,3,ABBVIE
46,4,ABL
128,5,ACCORD
161,6,ACHÉ
199,7,ADC
200,8,ADIUM
209,9,AIRELA
212,10,ALCON
215,11,ALEXION
217,12,ALLERGAN
225,13,ALLTRION
228,14,ALNYLAM
232,15,ALTANA
235,16,ALTEFAR
237,17,ALTHAIA
245,18,AMGEN
263,19,ANG
264,20,APSEN
287,21,ARESE
289,22,ARROW
290,23,ARTE NATIVA
293,24,ASOFARMA
294,25,ASP
297,26,ASTA MEDICA
299,27,ASTELLAS
307,28,ASTRAZENECA
516,112,FIOCRUZ
543,237,PFIZER
567,29,AUROBINDO
592,30,AVENTIS
595,31,AVERT
597,32,AVEXIS
598,33,B. BRAUN
629,34,BAGO
642,35,BALDACCI
644,37,BAUSCH LOMB
648,38,BAXALTA
653,39,BAXTER
697,40,BAYER
722,41,BEKER
727,42,BELCHER
731,43,BELFAR
736,44,BELIVE MEDICAL
740,45,BERGAMO
764,46,BESINS
768,47,BIEM ILAC
772,48,BIOCON
774,49,BIOGEN
784,50,BIOLAB
798,51,BIOMARIN
802,52,BIOMM
805,53,BIONATUS
807,54,BIONTECH
821,55,BIOPAS
823,56,BIOPHARMA
827,57,BIOSINTÉTICA
843,58,BIPSO GMBH
850,59,BLANVER
856,60,BLAU
963,61,BOEHRINGER INGELHEIM
991,62,BOYA
998,63,BRACCO
1000,64,BRACCO IMAGING
1036,65,BRACE PHARMA
1041,66,BRAINFARMA
1058,67,BRASMEDICA
1059,68,BRASTERAPICA
1062,69,BRISTOL
1111,70,CAMBER
1116,71,CATARINENSE
1122,72,CAZI
1124,73,CELGENE
1129,74,CELLERA
1141,75,CELLTRION
1180,76,CHIESI
1197,77,CHUGAI PHARMA
1202,78,CIFARMA
1204,79,CIMED
1225,80,CIPLA
1228,81,CITOPHARMA
1229,82,COSMED
1247,83,CRISTALIA
1418,84,CSL BEHRING
1427,85,CSL VIFOR PHARMA
1430,86,CTBB
1433,87,DAIICHI SANKYO
1450,88,DISAQ
1452,89,DIVCOM
1453,90,DLA PHARMA
1456,91,DR REDDYS
1478,92,DUOFLAN
1479,93,DUPATRI
1480,94,DUPRATI
1481,95,DURABENDO
1482,96,EISAI
1487,97,ELI LILLY
1511,98,ELLTRION
1512,99,ELMECO
1513,100,EMS
1616,101,EUGIA
1623,102,EUROFARMA
1710,103,EVOLABIS
1713,104,EXSELL
1717,105,FAP
1722,106,FARMACE
1753,107,FARMACO URUGAYO
1761,108,FARMAQUIMICA
1762,109,FARMARIN
1780,110,FARMAX
1781,111,FERRING
1982,113,FQM
2014,114,FRESENIUS KABI
2074,115,FUAN
2075,116,FUNED
2077,117,FURP
2090,118,GALDERMA
2092,119,GAN & LEE
2099,120,GE HEALTHCARE
2135,121,GEDEON RICHTER
2139,122,GENOMMA
2141,123,GENON
2145,124,GEOLAB
2155,125,GERMED
2166,126,GILEAD
2180,127,GLAND
2185,128,GLAXOSMITHKLINE
2248,129,GLENMARK
2281,130,GLOBO
2290,131,GREENPHARMA
2295,132,GRIFOLS
2303,133,GROSS
2304,134,GRUNENTHAL
2311,135,GUANGDONG SHUANGLIN
2315,136,GUEBERT
2321,137,GUERBET
2369,138,GUILEAD
2370,139,HALEON
2371,140,HALEX ISTAR
2439,141,HALLER
2440,142,HEBRON
2441,143,HEMAFARMA
2443,144,HEMOBRAS
2448,145,HERBARIUM
2452,146,HEXAL
2454,147,HIPOFARMA
2455,148,HIPOLABOR
2532,149,HISAMITSU
2533,150,HORIZON
2535,151,HOSPFARMA
2541,152,HYPERA PHARMA
2546,153,HYPOFARMA
2590,154,ICHOR
2604,155,IDT BIOLOGIKA GMBH
2606,156,IFAL
2607,157,IMEX MEDICAL
2613,158,IMMUNOMEDICS
2614,159,INFAN
2616,160,INSTITUTO BIOCHIMICO
2647,161,INSTITUTO BUTANTAN
2706,162,INTAS
2721,163,INTEGRAL MEDICA
2722,164,IPSEN
2728,165,ISOFARMA
2734,166,JACOBUS
2735,167,JOHNSON & JOHNSON
2896,168,JP INDUSTRIA FARMACEUTICA
2901,169,KENVUE
2902,170,KIRKLAND
2904,171,KITE PHARMA
2906,172,KLEY HERTZ
2911,173,KOCAK FARMA
2913,174,KOPLAN
2914,175,KWALITY
2916,176,LABORATORIO FARMACEUTICO DA MARINHA
2918,177,LABORATORIO FARMACEUTICO DO ESTADO DE PERNAMBUCO E TORRENT P
2919,178,LABORATORIO FARMACEUTICO DO EXERCITO
2925,179,LABORATORIO FARMACEUTICO MARINHA
2926,180,LABORATORIO FARMAEUTICO DO ESTADO DE PERNAMBUCO
2927,36,BASI
2929,181,LCC
2930,182,LEGRAND
2941,183,LEK
2947,184,LIBBS
2998,185,LIFE
2999,186,LTS
3003,187,LUNDBECK
3008,188,LUPIN
3016,189,MACLEODS
3025,190,MAIVA PHARMA
3027,191,MALLINCKRODT
3036,192,MANTECORP
3051,193,MARJAN
3057,194,MAWDSLEYS
3061,195,MAYA BIOTECH
3064,196,MEDCOR
3065,197,MEDICAMENTO MANIPULADO
3201,198,MEDLEY
3235,199,MEDQUIMICA
3244,200,MEIZLER
3246,201,MELCON
3247,202,MERCK
3314,203,MGC PHARMA
3315,204,MIDFARMA
3317,205,MIREK SHARPS DOME
3318,206,MODERNA
3323,207,MOMENTA
3327,208,MSD
3342,209,MULTIFARMA
3344,210,MULTILAB
3349,211,MUNDIPHARMA
3356,212,MYLAN
3374,213,MYRALIS
3378,214,NATUBRAS
3380,215,NATULAB
3385,216,NEEDS
3386,217,NEOQUIMICA
3396,218,NESTLE
3397,219,NEUVYE
3398,220,NOVA QUIMICA
3404,221,NOVAFARMA
3423,222,NOVAMED
3433,223,NOVARTIS
3491,224,NOVO NORDISK
3519,225,NUTRIUM
3520,226,OCTAPHARMA
3523,227,OFT VISION
3525,228,OLAINFARMA
3526,229,ONEFARMA
3527,230,OPEN
3540,231,OPHTHALMOS ROHTO
3548,232,ORGANON
3553,233,OTSUKA AMERICA
3555,234,OXALIS
3557,235,PANACEA BIOTEC
3563,236,PATHEON
3836,238,PHARLAB
3846,239,PHARMASCIENCE
3851,240,PIERRE FABRE
3858,241,PIERRE FABRI
3859,242,PINT FARMA
3866,243,PINT PHARMA
3874,244,PORTON
3875,245,PRATI DONADUZZI
3930,246,PROCTER GAMBLE
3933,247,PROMEFARMA
3934,248,PROMEL
3935,249,PROQUAD
3936,250,PROTECH
3940,251,PTC
3941,252,RANBAXY
3953,253,RAVIMED
3955,254,RECKITT
3958,255,RECORDATI RARE DISEASES BRASIL
3963,256,RIOQUIMICA
3968,257,ROCHE
4009,258,ROVI PHARMA INDUSTRIAL SERVICES
4010,259,ROXANE LABORATORIES
4012,260,ROYTON
4013,261,RUSAN
4015,262,SAMSUNG BIOEPIS
4024,263,SAMTEC
4030,264,SANDOZ
4076,265,SANIBIOL
4077,266,SANOFI
4079,0,NaN