#  ⭐ `dim_atc`

In [1]:
%run ../../config/bootstrap.py


from pathlib import Path
from utils import get_project_root , normalize_atc
 
import pandas as pd

In [2]:
project_root = get_project_root()

# 🥉 Bronze 

Raw Data
as is production, low quality

### ATC

In [3]:
bronze_atc = pd.read_excel(Path(project_root) / "data/01_bronze/atc/2025 ATC index with DDDs_english.xlsx")  
renomear = {
    "ATC code": "CODIGO_ATC_LEVEL",
    "ATC level name": "NIVEL_NOME_ATC",
    "DDD": "DDD_VALOR",
    "Unit": "DDD_UNIDADE",
    "Adm.R": "DDD_ADMINISTRACAO",
    "Comment": "DDD_COMENTARIO",
}

bronze_atc = bronze_atc.rename(columns=renomear)

In [4]:
bronze_atc.head(20)

,CODIGO_ATC_LEVEL,NIVEL_NOME_ATC,DDD_VALOR,DDD_UNIDADE,DDD_ADMINISTRACAO,DDD_COMENTARIO
0,A,ALIMENTARY TRACT AND METABOLISM,NaN,NaN,NaN,NaN
1,A01,STOMATOLOGICAL PREPARATIONS,NaN,NaN,NaN,NaN
2,A01AA,Caries prophylactic agents,NaN,NaN,NaN,NaN
3,A01AA01,sodium fluoride,1.10,mg,O,0.5 mg fluoride
4,A01AA02,sodium monofluorophosphate,NaN,NaN,NaN,NaN
5,A01AA03,olaflur,1.10,mg,O,NaN
6,A01AA04,stannous fluoride,NaN,NaN,NaN,NaN
7,A01AA30,combinations,NaN,NaN,NaN,NaN
8,A01AA51,"sodium fluoride, combinations",NaN,NaN,NaN,NaN
9,A01A,STOMATOLOGICAL PREPARATIONS,NaN,NaN,NaN,NaN
10,A01AB,Antiinfectives and antiseptics for local oral treatment,NaN,NaN,NaN,NaN
11,A01AB02,hydrogen peroxide,60.00,mg,O,NaN
12,A01AB03,chlorhexidine,30.00,mg,O,NaN
13,A01AB04,amphotericin B,40.00,mg,O,NaN
14,A01AB05,polynoxylin,0.18,g,O,NaN
15,A01AB06,domiphen,3.00,mg,O,NaN
16,A01AB07,oxyquinoline,80.00,mg,O,NaN
17,A01AB08,neomycin,NaN,NaN,NaN,NaN
18,A01AB09,miconazole,0.20,g,O,NaN
19,A01AB10,natamycin,20.00,mg,O,NaN

In [5]:
bronze_atc[bronze_atc["NIVEL_NOME_ATC"].str.contains("oxyquinoline", case=False, na=False)].head(20)

,CODIGO_ATC_LEVEL,NIVEL_NOME_ATC,DDD_VALOR,DDD_UNIDADE,DDD_ADMINISTRACAO,DDD_COMENTARIO
16,A01AB07,oxyquinoline,80.0,mg,O,NaN
465,A07AX01,broxyquinoline,NaN,NaN,NaN,NaN
2483,D08AH03,oxyquinoline,NaN,NaN,NaN,NaN
2656,G01AC01,diiodohydroxyquinoline,0.2,g,V,NaN
2660,G01AC06,broxyquinoline,0.1,g,V,NaN
2661,G01AC30,oxyquinoline,NaN,NaN,NaN,NaN
5898,P01AA,Hydroxyquinoline derivatives,NaN,NaN,NaN,NaN
5899,P01AA01,broxyquinoline,NaN,NaN,NaN,NaN
6175,R02AA14,oxyquinoline,NaN,NaN,NaN,NaN

In [6]:
bronze_atc.columns

Index(['CODIGO_ATC_LEVEL', 'NIVEL_NOME_ATC', 'DDD_VALOR', 'DDD_UNIDADE',
       'DDD_ADMINISTRACAO', 'DDD_COMENTARIO'],
      dtype='object')

In [7]:
bronze_atc[['CODIGO_ATC_LEVEL', 'NIVEL_NOME_ATC']].describe()

       CODIGO_ATC_LEVEL NIVEL_NOME_ATC
count              7435           7435
unique             6897           6045
top             G03CA03   combinations
freq                 10             38

### MEDICAMENTOS

In [8]:
 
bronze = pd.read_parquet(Path(project_root) / "data/01_bronze/Medicamentos/Medicamentos.parquet") 
bronze = bronze[['NOME_MEDICAMENTO_WHODRUG', 'PRINCIPIOS_ATIVOS_WHODRUG', 'CODIGO_ATC']].drop_duplicates()
bronze.head(20)

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC
0,Oxacilina,Oxacillin sodium,J01CF
1,Paracemol,Paracetamol,N02BE
2,Diamox,Acetazolamide sodium,C03|N03AX|S01EC
3,Hidantal,Phenytoin,N03AB
4,Nitroglicerina,Glyceryl trinitrate,C01DA|C05AE
5,Macrodantina,Nitrofurantoin,J01XE
6,Dexa-Citoneurin,Cyanocobalamin|Dexamethasone|Pyridoxine hydrochloride|Thiamine hydrochloride,H02BX
7,Benzetacil,Benzathine benzylpenicillin,J01CE
8,Reuquinol,Hydroxychloroquine sulfate,P01BA
9,Anfotericina b,Amphotericin b,J02AA
10,Oxaliplatina,Oxaliplatin,L01XA
11,Dimorf,Morphine sulfate,N02AA
16,Gynera,Ethinylestradiol|Gestodene,G03AA
17,Hetori,Etoricoxib,M01AH
18,Genuxal,Cyclophosphamide,L01AA
19,Dipirona,Metamizole sodium,N02BB
20,Docelibbs,Docetaxel,L01CD
21,Cetoprofeno,Ketoprofen,M01AE|M02AA
22,Gentamicin,Gentamicin,D06AX|J01GB|S01AA|S02AA|S03AA
23,Ondansetron,Ondansetron,A04AA

In [9]:
bronze.describe()

       NOME_MEDICAMENTO_WHODRUG PRINCIPIOS_ATIVOS_WHODRUG CODIGO_ATC
count                     20224                     20124      20224
unique                    12490                      6501       2315
top                     Calcium            Colecalciferol      J01CR
freq                         19                        60        315

In [10]:
bronze[bronze["NOME_MEDICAMENTO_WHODRUG"].str.contains("oxyquinoline", case=False, na=False)].head(20)

Empty DataFrame
Columns: [NOME_MEDICAMENTO_WHODRUG, PRINCIPIOS_ATIVOS_WHODRUG, CODIGO_ATC]
Index: []

In [11]:
bronze[bronze["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("oxyquinoline", case=False, na=False)].head(20)

,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC
28579,Cerumin,Hydroxyquinoline borate|Trolamine,S02DC
251441,Malvatricin,Hydroxyquinoline sulfate|Tyrothricin,A01AB|R02AB
300362,Malvatricin,Hydroxyquinoline sulfate|Lidocaine hydrochloride|Tyrothricin,A01AD|R02AX
331509,Cerumin,Hydroxyquinoline borate_x000D_|Trolamine,S02DC

# 🥈 Silver

normalized data, medium quality

In [12]:
silver = bronze.copy()

In [ ]:
hist = normalize_atc(silver, bronze_atc, threshold=82)
hist.head()

In [ ]:
hist[hist["PRINCIPIOS_ATIVOS_WHODRUG"].str.contains("oxyquinoline", case=False, na=False)].head(20)

In [ ]:
hist.to_csv(Path(project_root) / "data/02_silver/hist_dim_atc/hist_dim_atc_MANUAL.csv", sep=";")

Index(['DETENTOR_REGISTRO', 'DETENTOR_REGISTRO_PADRONIZADO'], dtype='object')

In [ ]:
silver.head(2)

  DETENTOR_REGISTRO DETENTOR_REGISTRO_PADRONIZADO
0   ABACUS MEDICINE               ABACUS MEDICINE
1            ABBOLT                         ABBOT

# 🥇 Gold

In [ ]:
hist.columns

Index(['DETENTOR_REGISTRO', 'DETENTOR_REGISTRO_PADRONIZADO',
       'DETENTOR_REGISTRO_CHAVE', 'DETENTOR_REGISTRO_VALOR'],
      dtype='object')

In [ ]:
#dim = hist[['DETENTOR_REGISTRO_CHAVE', 'DETENTOR_REGISTRO_VALOR']].drop_duplicates()
#dim.to_parquet(Path(project_root) / "data/03_gold/dim_detentor_registro/dim_detentor_registro.parquet", index=False)

In [ ]:

#dim.to_csv(Path(project_root) / "data/03_gold/dim_detentor_registro/dim_detentor_registro.csv", sep=";", index=False)