In [ ]:
%run ../config/bootstrap.py

### Libs

In [ ]:
import pandas as pd
from pathlib import Path
from utils import get_project_root

In [ ]:
project_root = get_project_root()

# Datasets

In [ ]:
path = Path(project_root) / "data/02_silver/Medicamentos/dim_medicamentos_25092025.parquet"
df_medicamentos = pd.read_parquet(path) 
df_medicamentos = df_medicamentos.drop_duplicates()
df_medicamentos.head()

,IDENTIFICACAO_NOTIFICACAO,RELACAO_MEDICAMENTO_EVENTO,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,CODIGO_ATC,DETENTOR_REGISTRO,CONCENTRACAO,COMPONENTE_SUSPEITO,ACAO_ADOTADA,PROBLEMAS_ADICIONAIS_RELCIONADOS_MEDICAMENTO,INDICACAO_MEDDRA,INDICACAO_RELATADA_NOTIFICADOR_INICIAL,DOSE,FREQUENCIA_DOSE,POSOLOGIA,DURACAO,INICIO_ADMINISTRACAO,FIM_ADMINISTRACAO,FORMA_FARMACEUTICA,VIA_ADMINISTRACAO,VIA_ADMINISTRACAO_MAE_PAI,NUMELO_LOTE,hash,current_flag,start_date,end_date
0,BR-ANVISA-300000004,SUSPEITO,OXACILINA,OXACILLIN SODIUM,J01CF,TEUTO,NONE,NONE,NONE,NONE,NONE,NONE,250 MILLIGRAM (MG),6 HORA,NONE,4 DIA,2018-11-24,NaT,NONE,INFUSÃO INTRAVENOSA,NONE,5833018,6dfd9bbed05c3382d017471f9716f9709e8fad84070483c023972f35ff650c40,True,2025-09-25 17:20:10.098855,NaT
1,BR-ANVISA-300000005,SUSPEITO,PARACEMOL,PARACETAMOL,N02BE,NONE,NONE,NONE,RETIRADA DO MEDICAMENTO,NONE,NONE,NONE,NONE,NONE,NONE,NONE,2018-11-22,2018-11-22,NONE,ORAL,NONE,NONE,5c8a6481fc8ae84cba91620f62f84a5d3c8db77119d6c76a0ec3eb3e590a835b,True,2025-09-25 17:20:10.098855,NaT
2,BR-ANVISA-300000007,SUSPEITO,DIAMOX,ACETAZOLAMIDE SODIUM,C03|N03AX|S01EC,NONE,NONE,NONE,RETIRADA DO MEDICAMENTO,NONE,NONE,NONE,250 MILLIGRAM (MG),6 HORA,250MG A CADA 6 HORAS,NONE,2018-11-03,2018-11-15,NONE,ORAL,NONE,NONE,24b5b6296de2783a22454446ffe89d8ebf12670c5801f57c089acebce39f42e7,True,2025-09-25 17:20:10.098855,NaT
3,BR-ANVISA-300000007,SUSPEITO,HIDANTAL,PHENYTOIN,N03AB,NONE,NONE,NONE,RETIRADA DO MEDICAMENTO,NONE,NONE,NONE,NONE,NONE,100MG A CADA 8 HORAS,NONE,2018-10-16,2018-11-15,NONE,ORAL,NONE,NONE,77383395999894b616432d7b50fdd36f7f29f30accd14b7e544479068e30bad2,True,2025-09-25 17:20:10.098855,NaT
4,BR-ANVISA-300000008,SUSPEITO,NITROGLICERINA,GLYCERYL TRINITRATE,C01DA|C05AE,CRISTÁLIA,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,2018-10-24,NaT,NONE,INFUSÃO INTRAVENOSA,NONE,NONE,3c49b163f7092eafd0c2fe7ee6a932a69c5ef23a9399fcd1f422a197ca276556,True,2025-09-25 17:20:10.098855,NaT

In [ ]:
path = Path(project_root) / "data/02_silver/Notificacoes/fat_notificacoes_25092025.parquet"
df_notificacoes = pd.read_parquet(path) 
df_notificacoes = df_notificacoes.drop_duplicates()
df_notificacoes.head()

,UF,TIPO_ENTRADA_VIGIMED,RECEBIDO_DE,IDENTIFICACAO_NOTIFICACAO,DATA_INCLUSAO_SISTEMA,DATA_ULTIMA_ATUALIZACAO,DATA_NOTIFICACAO,TIPO_NOTIFICACAO,NOTIFICACAO_PARENT_CHILD,DATA_NASCIMENTO,IDADE_MOMENTO_REACAO,GRUPO_IDADE,IDADE_GESTACIONAL_MOMENTO_REACAO,SEXO,GESTANTE,LACTANTE,PESO_KG,ALTURA_CM,REACAO_EVENTO_ADVERSO_MEDDRA,GRAVE,GRAVIDADE,DESFECHO,DATA_INICIO_HORA,DATA_FINAL_HORA,DURACAO,RELACAO_MEDICAMENTO_EVENTO,NOME_MEDICAMENTO_WHODRUG,ACAO_ADOTADA,NOTIFICADOR,hash,hash_med,hash_reac
0,SP,EMPRESAS FARMACĘUTICAS,EMPRESA FARMACĘUTICA,BR-ANVISA-300212656,2023-09-28,2023-09-28,NaT,NOTIFICAÇĂO ESPONTÂNEA,NONE,1990-01-31,30 ANO,NONE,NONE,FEMININO,NĂO,NĂO,68.0,165,HEMIPARESIA,SIM,OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO,RECUPERADO,2021-01-25,2021-02-06,12 DIA,CONCOMITANTE,TAMISA,NĂO APLICÁVEL,MÉDICO,9ca67eed7623eebbcaebe79a7948bd7b29e27a91a8cecd7a6dbbec1660721572,6a496f4c0b981b263f1d42856468abd9f50b05001e49c610071cbebc8c65e936,b470994c52b6ce0bcfdfa545eb2afeefb150eefef702798ae69be1258ef4c688
1,SP,EMPRESAS FARMACĘUTICAS,EMPRESA FARMACĘUTICA,BR-ANVISA-300212656,2023-09-28,2023-09-28,NaT,NOTIFICAÇĂO ESPONTÂNEA,NONE,1990-01-31,30 ANO,NONE,NONE,FEMININO,NĂO,NĂO,68.0,165,HEMIPARESIA,SIM,OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO,RECUPERADO,2021-01-25,2021-02-06,12 DIA,CONCOMITANTE,TAMISA,NĂO APLICÁVEL,MÉDICO,9ca67eed7623eebbcaebe79a7948bd7b29e27a91a8cecd7a6dbbec1660721572,afea4791611e192c13403e2c9710f2eb6270ea1866a9d86159117fc104721645,b470994c52b6ce0bcfdfa545eb2afeefb150eefef702798ae69be1258ef4c688
2,SP,EMPRESAS FARMACĘUTICAS,EMPRESA FARMACĘUTICA,BR-ANVISA-300212656,2023-09-28,2023-09-28,NaT,NOTIFICAÇĂO ESPONTÂNEA,NONE,1990-01-31,30 ANO,NONE,NONE,FEMININO,NĂO,NĂO,68.0,165,HEMIPARESIA,SIM,OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO,RECUPERADO,2021-01-25,2021-02-06,12 DIA,CONCOMITANTE,TAMISA,NĂO APLICÁVEL,MÉDICO,9ca67eed7623eebbcaebe79a7948bd7b29e27a91a8cecd7a6dbbec1660721572,c1677cb915d1da7afb44d5184e6fa74c2e9ea93f40258a133869c7462626737a,b470994c52b6ce0bcfdfa545eb2afeefb150eefef702798ae69be1258ef4c688
3,SP,EMPRESAS FARMACĘUTICAS,EMPRESA FARMACĘUTICA,BR-ANVISA-300212656,2023-09-28,2023-09-28,NaT,NOTIFICAÇĂO ESPONTÂNEA,NONE,1990-01-31,30 ANO,NONE,NONE,FEMININO,NĂO,NĂO,68.0,165,HEMIPARESIA,SIM,OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO,RECUPERADO,2021-01-25,2021-02-06,12 DIA,CONCOMITANTE,TAMISA,NĂO APLICÁVEL,MÉDICO,9ca67eed7623eebbcaebe79a7948bd7b29e27a91a8cecd7a6dbbec1660721572,44038d6f81317f1d55887bdd2c76308769edca660cb252f338d903ae0ef8f6f4,b470994c52b6ce0bcfdfa545eb2afeefb150eefef702798ae69be1258ef4c688
4,SP,EMPRESAS FARMACĘUTICAS,EMPRESA FARMACĘUTICA,BR-ANVISA-300208322,2023-09-01,2023-09-01,NaT,NOTIFICAÇĂO ESPONTÂNEA,NONE,NaT,NONE,NONE,NONE,FEMININO,NĂO,NĂO,NONE,NONE,CEFALEIA,NĂO,OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO,DESCONHECIDO,2021-01-22,NaT,NONE,SUSPEITO,CORONAVAC,NĂO APLICÁVEL,CONSUMIDOR OU OUTRO NĂO PROFISSIONAL DE SAÚDE,a2a4e923072a589154238b6f4a4004148304814272d8ec7d46f18e115060fe68,1a0df810e3c2d3dac85a922009858d99cc6c0ef3263989b91dc533a73bfcd0ff,3d6f108ec7334a1302f115c552765390aafe1fa8105b9aa4c0cc0e7a82715bed

In [ ]:
path = Path(project_root) / "data/02_silver/Reacoes/dim_reacoes_25092025.parquet"
df_reacoes = pd.read_parquet(path) 
df_reacoes = df_reacoes.drop_duplicates()
df_reacoes.head()

NameError: name 'df_reacoes' is not defined

In [7]:
=====

SyntaxError: invalid syntax (1414413079.py, line 1)

# IDENTIFICACAO_NOTIFICACAO

In [ ]:
df_notificacoes.query("IDENTIFICACAO_NOTIFICACAO == 'BR-ANVISA-300347639'")

,1616897,1616898
UF,SP,SP
TIPO_ENTRADA_VIGIMED,"EREPORTING - INDÚSTRIA, ENTRADA MANUAL DE DADOS","EREPORTING - INDÚSTRIA, ENTRADA MANUAL DE DADOS"
RECEBIDO_DE,EMPRESA FARMACĘUTICA,EMPRESA FARMACĘUTICA
IDENTIFICACAO_NOTIFICACAO,BR-ANVISA-300347639,BR-ANVISA-300347639
DATA_INCLUSAO_SISTEMA,2025-08-01 00:00:00,2025-08-01 00:00:00
DATA_ULTIMA_ATUALIZACAO,2025-08-01 00:00:00,2025-08-01 00:00:00
DATA_NOTIFICACAO,NaT,NaT
TIPO_NOTIFICACAO,NOTIFICAÇĂO ESPONTÂNEA,NOTIFICAÇĂO ESPONTÂNEA
NOTIFICACAO_PARENT_CHILD,NONE,NONE
DATA_NASCIMENTO,2005-02-15 00:00:00,2005-02-15 00:00:00
IDADE_MOMENTO_REACAO,NONE,NONE
GRUPO_IDADE,NONE,NONE
IDADE_GESTACIONAL_MOMENTO_REACAO,NONE,NONE
SEXO,FEMININO,FEMININO
GESTANTE,NĂO,NĂO
LACTANTE,NĂO,NĂO
PESO_KG,40,40
ALTURA_CM,165,165
REACAO_EVENTO_ADVERSO_MEDDRA,DOENÇA DE CROHN,DOENÇA DE CROHN
GRAVE,SIM,SIM
GRAVIDADE,HOSPITALIZAÇĂO,HOSPITALIZAÇĂO
DESFECHO,NĂO RECUPERADO,NĂO RECUPERADO
DATA_INICIO_HORA,NaT,NaT
DATA_FINAL_HORA,NaT,NaT
DURACAO,NONE,NONE
RELACAO_MEDICAMENTO_EVENTO,SUSPEITO,SUSPEITO
NOME_MEDICAMENTO_WHODRUG,STELARA,STELARA
ACAO_ADOTADA,DESCONHECIDO,DESCONHECIDO
NOTIFICADOR,CONSUMIDOR OU OUTRO NĂO PROFISSIONAL DE SAÚDE,CONSUMIDOR OU OUTRO NĂO PROFISSIONAL DE SAÚDE
hash,0296d957cbe6942a7a176bd42a99d33d0d236aefae77152dff6b021473cb5bf8,0296d957cbe6942a7a176bd42a99d33d0d236aefae77152dff6b021473cb5bf8
hash_med,1229f8e5c05441b19bee0af4bf0f2d0fd35873532256eddf20e06ff35c20a585,1229f8e5c05441b19bee0af4bf0f2d0fd35873532256eddf20e06ff35c20a585
hash_reac,cdced2fa14d1ba0fcf198a42d1ffca76d61e4ae2342aee100dd692babf530be3,5f0c5d5796361676fd468382ca19994a5e06de4501211d4d945d1e50b974dedd

In [ ]:
df_medicamentos.query("IDENTIFICACAO_NOTIFICACAO == 'BR-ANVISA-300347639'")

                                                                                                        552735
IDENTIFICACAO_NOTIFICACAO                                                                  BR-ANVISA-300347639
RELACAO_MEDICAMENTO_EVENTO                                                                            SUSPEITO
NOME_MEDICAMENTO_WHODRUG                                                                               STELARA
PRINCIPIOS_ATIVOS_WHODRUG                                                                        USTEQUINUMABE
CODIGO_ATC                                                                                               L04AC
DETENTOR_REGISTRO                                                                                         NONE
CONCENTRACAO                                                                                              NONE
COMPONENTE_SUSPEITO                                                                                       NONE
ACAO_ADOTADA                                                                                      DESCONHECIDO
PROBLEMAS_ADICIONAIS_RELCIONADOS_MEDICAMENTO                                                              NONE
INDICACAO_MEDDRA                                                                               DOENÇA DE CROHN
INDICACAO_RELATADA_NOTIFICADOR_INICIAL                                                                    NONE
DOSE                                                                                                      NONE
FREQUENCIA_DOSE                                                                                       8 SEMANA
POSOLOGIA                                                                                                 NONE
DURACAO                                                                                                   NONE
INICIO_ADMINISTRACAO                                                                                       NaT
FIM_ADMINISTRACAO                                                                                          NaT
FORMA_FARMACEUTICA                                                                                        NONE
VIA_ADMINISTRACAO                                                                                         NONE
VIA_ADMINISTRACAO_MAE_PAI                                                                                 NONE
NUMELO_LOTE                                                                                               NONE
hash                                          1229f8e5c05441b19bee0af4bf0f2d0fd35873532256eddf20e06ff35c20a585
current_flag                                                                                              True
start_date                                                                          2025-09-25 17:20:10.098855
end_date                                                                                                   NaT

In [ ]:
df_reacoes.query("IDENTIFICACAO_NOTIFICACAO == 'BR-ANVISA-300347639'")

## Dicionario Medicamentos

In [ ]:
codigo_atc = ['']