# 🥉 Bronze | atc

Raw Data
as is production, low quality

In [4]:
%run ../config/bootstrap.py

import pandas as pd 
from pathlib import Path
from utils import get_project_root 
project_root = get_project_root()

In [6]:
file_path = Path(project_root) / "data/01_bronze/atc/2025 ATC index with DDDs_english.xlsx"
xls = pd.ExcelFile(file_path)  # você só "abre" o arquivo
print(xls.sheet_names)

['ATC index with DDDs 2025', 'Copyright', 'Abbreviations', 'Additional information', 'DDD 3 Year revision']

## Copyright

In [11]:
c = pd.read_excel(file_path, sheet_name="Copyright")
c.head()

                                                                                                                                                                                                                                                                                                               © Copyright
0  WHO Collaborating Centre for Drug Statistics Methodology, Oslo, Norway. Use of all or parts of the material requires reference to the WHO Collaborating Centre for Drug Statistics Methodology.  Copying and distribution for commercial purposes is not allowed.  Changing or manipulating the material is not allowed.

## Abbreviations

In [10]:
dim_abr = pd.read_excel(file_path, sheet_name="Abbreviations")
dim_abr

,"Units, abbreviations",Unnamed: 1,Unnamed: 2
0,g,=,gram
1,mg,=,milligram
2,mcg,=,microgram
3,U,=,unit
4,TU,=,thousand units
5,MU,=,million units
6,mmol,=,millimole
7,ml,=,milliliter
8,NaN,NaN,(e.g. eyedrops)
9,NaN,NaN,NaN
10,"Route of administration (Adm.R), abbreviations",NaN,NaN
11,Implant,=,implant
12,Inhal,=,inhalation
13,Instill,=,instillation
14,N,=,nasal
15,O,=,oral
16,P,=,parenteral
17,R,=,rectal
18,SL,=,sublingual/buccal/oromucosal
19,TD,=,transdermal
20,V,=,vaginal

## Additional information

In [ ]:
addInfo = pd.read_excel(file_path, sheet_name="Additional information")
addInfo

,Additional information,Links
0,"New ATC codes, DDDs and alterations decided during the year (updated biannually)",https://atcddd.fhi.no/lists_of__temporary_atc_ddds_and_alterations/
1,DDDs for fixed combination products given in unit dose (UD),https://atcddd.fhi.no/ddd/list_of_ddds_combined_products/
2,Cumulative lists of ATC and DDD alterations,https://atcddd.fhi.no/atc_ddd_alterations__cumulative/ddd_alterations/
3,Searchable version of the ATC/DDD Index with integrated texts form Guidelines,https://atcddd.fhi.no/atc_ddd_index/
4,Application form new ATC/DDD and alterations,https://atcddd.fhi.no/atc/application_form/

## DDD 3 Year revision

In [13]:
ddd3y = pd.read_excel(file_path, sheet_name="DDD 3 Year revision")
ddd3y

,ATC code,ATC level name,New DDD,Unit,Adm.route,Note
0,B02BX09,fostamatinib,0.200,g,O,NaN
1,B03XA05,roxadustat,43.000,mg,O,NaN
2,B06AC06,berotralstat,0.150,g,O,NaN
3,C01DX22,vericiguat,10.000,mg,O,NaN
4,C10AX15,bempedoic acid,0.180,g,O,NaN
5,C10AX16,inclisiran,1.600,mg,P,NaN
6,C10AX18,volanesorsen,20.000,mg,P,NaN
7,D11AH07,tralokinumab,16.100,mg,P,NaN
8,D11AH08,abrocitinib,0.150,g,O,NaN
9,G01AF21,tinidazole,0.200,g,V,NaN
10,J01GB06,amikacin,0.590,g,Inhal.solution,NaN
11,J05AB18,molnupiravir,1.600,g,O,NaN
12,J05AE30,nirmatrelvir and ritonavir,0.600,g,O,refers to nirmatrelvir
13,J06BD05,sotrovimab,0.500,g,P,NaN
14,L04AC21,bimekizumab,5.700,mg,P,NaN
15,L04AE04,ponesimod,20.000,mg,O,ATC code L04AA50 altered Index 2024
16,L04AF04,filgotinib,0.200,g,O,ATC code L04AA45 altered Index 2024
17,L04AG12,ofatumumab,0.670,mg,P,ATC code L04AA52 altered Index 2024
18,L04AJ05,avacopan,60.000,mg,O,ATC code L04AA59 altered Index 2024
19,L04AX09,diroximel fumarate,0.924,g,O,NaN
20,M05BX05,burosumab,2.500,mg,P,NaN
21,M05BX06,romosozumab,7.000,mg,P,NaN
22,M09AX10,risdiplam,5.000,mg,O,NaN
23,N02CD06,rimegepant,37.500,mg,O,NaN
24,N03AX26,fenfluramine,8.000,mg,O,NaN
25,N07BC01,buprenorphine,1.600,mg,implant,NaN
26,N07XX15,inotersen,41.000,mg,P,NaN
27,P01CX04,miltefosine,0.150,g,O,NaN

## ATC index with DDDs 2025

In [14]:
dim_atc = pd.read_excel(file_path, sheet_name="ATC index with DDDs 2025")
dim_atc.head()

  ATC code                   ATC level name  DDD Unit Adm.R          Comment
0        A  ALIMENTARY TRACT AND METABOLISM  NaN  NaN   NaN              NaN
1      A01      STOMATOLOGICAL PREPARATIONS  NaN  NaN   NaN              NaN
2    A01AA       Caries prophylactic agents  NaN  NaN   NaN              NaN
3  A01AA01                  sodium fluoride  1.1   mg     O  0.5 mg fluoride
4  A01AA02       sodium monofluorophosphate  NaN  NaN   NaN              NaN