# 🥉 Bronze | MedDra Reacoes

Raw Data
as is production, low quality

In [1]:
%run ../config/bootstrap.py

import pandas as pd 
from pathlib import Path
from utils import get_project_root 
project_root = get_project_root()

# df

In [ ]:
eda/eda_meddra.ipynb
data/01_bronze/meddra/MedDRA_28_1_Brazilian_Portuguese/version_report_28_1_Brazilian_Portuguese.xlsx

In [2]:
file_path = Path(project_root) / "data/01_bronze/meddra/MedDRA_28_1_Brazilian_Portuguese/version_report_28_1_Brazilian_Portuguese.xlsx"
xls = pd.ExcelFile(file_path)  # você só "abre" o arquivo
print(xls.sheet_names)

['Resumo', 'Novos LLTs, incluindo novos PTs', 'Novos PTs', 'Promoções', 'Rebaixamentos', 'LLTs sob diferentes PTs', 'Alterações de SOC primário de L', 'Alterações de SOC primário do P', 'Alterações de nome de termo do ', 'Trocas de código do MedDRA', 'Alterações de vigência', 'Alterações complexas', 'Alterações de SMQ', 'Alterações de PT em SMQs', 'Alterações de LLT em SMQs']

## Resumo

In [3]:
r = pd.read_excel(file_path, sheet_name="Resumo")
r.head()

/Users/silmarabarnabe/Desktop/vigimed/.venv/lib/python3.9/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

,Título do relatório,Total de termos únicos entre as versões selecionadas,Relatório selecionado?
0,"Novos LLTs, incluindo novos PTs",697.0,Sim
1,Novos PTs,249.0,Sim
2,Promoções,14.0,Sim
3,Rebaixamentos,20.0,Sim
4,LLTs sob diferentes PTs,104.0,Sim

## LLTs sob diferentes PTs

In [4]:
llt_pt = pd.read_excel(file_path, sheet_name="LLTs sob diferentes PTs")
llt_pt.head()

/Users/silmarabarnabe/Desktop/vigimed/.venv/lib/python3.9/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

,Código do LLT,LLT,28.0 Código do PT,28.0 PT,28.1 Código do PT,28.1 PT,28.1 Vigência
0,10001190,Adenocarcinoma da cárdia em estágio 0,10001150,Adenocarcinoma gástrico,10001153,Adenocarcinoma gástrico em estágio 0,ou Vigente
1,10001191,Adenocarcinoma da cárdia em estágio I,10001150,Adenocarcinoma gástrico,10001154,Adenocarcinoma gástrico em estágio I,ou Vigente
2,10001192,Adenocarcinoma da cárdia em estágio II,10001150,Adenocarcinoma gástrico,10001155,Adenocarcinoma gástrico em estágio II,ou Vigente
3,10001193,Adenocarcinoma da cárdia em estágio III,10001150,Adenocarcinoma gástrico,10001156,Adenocarcinoma gástrico em estágio III,ou Vigente
4,10001195,Adenocarcinoma da cárdia em estágio IV com metástases,10001150,Adenocarcinoma gástrico,10092541,Adenocarcinoma gástrico em estágio IV,ou Vigente