## Atualizar a seção e abrir nova

In [15]:
%sql ROLLBACK;

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [Success]
Index: []

## Criar as tabela e fazer as consultas

In [17]:
%%sql
DROP TABLE IF EXISTS dim_soc;
CREATE TABLE dim_soc AS
SELECT * FROM read_parquet('/home/carolina/Área de trabalho/vigimed/data/03_gold/dim_soc/dim_soc.parquet');


DROP TABLE IF EXISTS fat_reacoes;
CREATE TABLE fat_reacoes AS
SELECT * FROM read_parquet('/home/carolina/Área de trabalho/vigimed/data/03_gold/fat_reacoes/fat_reacoes.parquet');

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [Success]
Index: []

In [9]:
%%sql
SELECT * 
FROM dim_soc
LIMIT 1;

Running query in 'duckdb:///:memory:'

,PK_SOC,SOC,HLGT,HLT,PT,PK_LLT,REACAO_EVTO_ADVERSO_MEDDRA_LLT
0,26,Circunstâncias sociais,Fatores relacionados ao gênero,Circunstâncias relacionadas à gravidez,Amamentação,1,Amamentação

In [11]:
%%sql
SELECT *
FROM fat_reacoes
LIMIT 1;

Running query in 'duckdb:///:memory:'

,IDENTIFICACAO_NOTIFICACAO,PK_SOC,PK_LLT,DATA_INICIO_HORA,DATA_FINAL_HORA,DURACAO,GRAVE,DESFECHO,ATUALIZADO,DURACAO_VALOR,DURACAO_TIPO,GRAVIDADE_RESULTADO_OBITO,GRAVIDADE_AMEACA_VIDA,GRAVIDADE_INCAPACIDADE,GRAVIDADE_HOSPITALIZACAO,GRAVIDADE_OUTRO_EFEITO,GRAVIDADE_ANOMALIA_CONGENITA
0,BR-ANVISA-300000004,16,4114,NaT,NaT,3 dia,2,3,2025-11-17,3.0,dia,0,0,0,0,0,0

# OK - DATA_INICIO_HORA

In [22]:
%%sql
SELECT DATA_INICIO_HORA,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC
LIMIT 10;

Running query in 'duckdb:///:memory:'

  DATA_INICIO_HORA      qt
0              NaT  468181
1       2020-01-02    1317
2       2020-01-01     987
3       2022-01-02     952
4       2021-01-01     950
5       2021-01-02     916
6       2021-05-20     866
7       2021-06-02     864
8       2022-01-01     829
9       2023-01-01     816

# OK- DATA_FINAL_HORA

In [25]:
%%sql
SELECT DATA_FINAL_HORA,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC
LIMIT 10;

Running query in 'duckdb:///:memory:'

  DATA_FINAL_HORA      qt
0             NaT  626402
1      2019-04-23     551
2      2021-06-05     455
3      2021-06-04     392
4      2021-06-06     385
5      2021-06-03     374
6      2021-05-20     354
7      2021-05-21     323
8      2021-05-22     322
9      2021-05-06     321

# OK- DURACAO
Ajuste sendo feito na fat_medicamentos

In [28]:
%%sql
SELECT DURACAO,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC
LIMIT 10;

Running query in 'duckdb:///:memory:'

     DURACAO      qt
0       None  688151
1      1 dia   27059
2      2 dia   10017
3      3 dia    6650
4     1 hora    6314
5  30 minuto    5865
6      4 dia    4278
7      5 dia    3707
8      0 dia    3349
9     2 hora    3112

# GRAVE

In [29]:
%%sql
SELECT GRAVE,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC
LIMIT 10;

Running query in 'duckdb:///:memory:'

   GRAVE      qt
0      2  374682
1      1  268114
2      0  173081

# DESFECHO

In [30]:
%%sql
SELECT DESFECHO,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC
LIMIT 10;

Running query in 'duckdb:///:memory:'

   DESFECHO      qt
0         0  362166
1         3  278670
2         1   85241
3         2   66908
4         4   18581
5         5    4311

# OK- ATUALIZADO

In [32]:
%%sql
SELECT ATUALIZADO,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC

Running query in 'duckdb:///:memory:'

   ATUALIZADO      qt
0  2025-11-17  815877

# DURACAO_VALOR

In [45]:
%%sql
SELECT DURACAO_VALOR,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC
LIMIT 10;

Running query in 'duckdb:///:memory:'

   DURACAO_VALOR      qt
0            NaN  688275
1            1.0   37128
2            2.0   15479
3            3.0    9917
4           30.0    6422
5            5.0    6190
6            4.0    6146
7           10.0    4270
8            6.0    3670
9            0.0    3481

In [47]:
%%sql
SELECT *
FROM fat_reacoes
WHERE DURACAO_VALOR ='1.50'
LIMIT 10;

Running query in 'duckdb:///:memory:'

,IDENTIFICACAO_NOTIFICACAO,PK_SOC,PK_LLT,DATA_INICIO_HORA,DATA_FINAL_HORA,DURACAO,GRAVE,DESFECHO,ATUALIZADO,DURACAO_VALOR,DURACAO_TIPO,GRAVIDADE_RESULTADO_OBITO,GRAVIDADE_AMEACA_VIDA,GRAVIDADE_INCAPACIDADE,GRAVIDADE_HOSPITALIZACAO,GRAVIDADE_OUTRO_EFEITO,GRAVIDADE_ANOMALIA_CONGENITA
0,BR-ANVISA-300036565,14,5693,NaT,NaT,1.5 hora,2,3,2025-11-17,1.5,hora,0,0,0,0,0,0
1,BR-ANVISA-300054316,11,260,NaT,NaT,1.5 hora,2,3,2025-11-17,1.5,hora,0,0,0,0,0,0
2,BR-ANVISA-300069861,16,4092,2021-06-30,2021-06-30,1.5 hora,2,3,2025-11-17,1.5,hora,0,0,0,0,0,0
3,BR-ANVISA-300087980,22,6126,2021-01-31,2021-02-12,1.5 semana,1,5,2025-11-17,1.5,semana,0,0,0,0,1,0
4,BR-ANVISA-300087980,13,10887,2021-01-31,2021-02-12,1.5 semana,1,5,2025-11-17,1.5,semana,0,0,0,0,1,0
5,BR-ANVISA-300087980,22,6526,2021-01-31,2021-02-12,1.5 semana,1,5,2025-11-17,1.5,semana,0,0,0,0,1,0
6,BR-ANVISA-300094307,3,3278,2021-10-13,2021-10-14,1.5 dia,2,2,2025-11-17,1.5,dia,0,0,0,0,0,0
7,BR-ANVISA-300095044,17,8206,2021-10-10,NaT,1.5 semana,1,1,2025-11-17,1.5,semana,0,0,0,0,1,0
8,BR-ANVISA-300106904,1,12547,2021-11-07,NaT,1.5 mês,1,2,2025-11-17,1.5,mês,0,0,0,0,1,0
9,BR-ANVISA-300108707,17,8231,NaT,NaT,1.5 hora,2,3,2025-11-17,1.5,hora,0,0,0,0,0,0

# DURACAO_TIPO

In [36]:
%%sql
SELECT DURACAO_TIPO,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC

Running query in 'duckdb:///:memory:'

   DURACAO_TIPO      qt
0          none  688151
1           dia   76020
2        minuto   24232
3          hora   17868
4           mês    5644
5        semana    2259
6           ano    1313
7       segundo     353
8  Desconhecido      24
9        década      13

# GRAVIDADE_RESULTADO_OBITO

In [38]:
%%sql
SELECT GRAVIDADE_RESULTADO_OBITO,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC

Running query in 'duckdb:///:memory:'

   GRAVIDADE_RESULTADO_OBITO      qt
0                          0  797247
1                          1   18630

# GRAVIDADE_AMEACA_VIDA

In [39]:
%%sql
SELECT GRAVIDADE_AMEACA_VIDA,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC

Running query in 'duckdb:///:memory:'

   GRAVIDADE_AMEACA_VIDA      qt
0                      0  794831
1                      1   21046

# GRAVIDADE_INCAPACIDADE

In [40]:
%%sql
SELECT GRAVIDADE_INCAPACIDADE,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC

Running query in 'duckdb:///:memory:'

   GRAVIDADE_INCAPACIDADE      qt
0                       0  802351
1                       1   13526

# GRAVIDADE_HOSPITALIZACAO

In [41]:
%%sql
SELECT GRAVIDADE_HOSPITALIZACAO,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC

Running query in 'duckdb:///:memory:'

   GRAVIDADE_HOSPITALIZACAO      qt
0                         0  729438
1                         1   86439

# GRAVIDADE_OUTRO_EFEITO

In [42]:
%%sql
SELECT GRAVIDADE_OUTRO_EFEITO,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC

Running query in 'duckdb:///:memory:'

   GRAVIDADE_OUTRO_EFEITO      qt
0                       0  641920
1                       1  173957

# GRAVIDADE_ANOMALIA_CONGENITA

In [43]:
%%sql
SELECT GRAVIDADE_ANOMALIA_CONGENITA,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC

Running query in 'duckdb:///:memory:'

   GRAVIDADE_ANOMALIA_CONGENITA      qt
0                             0  815429
1                             1     448