# **Coleta de dados**

In [1]:
#Bases de Dados 
from pathlib import Path
import pandas as pd
#import duckdb

# Visualização
import plotly.express as px

# Modelagem 
import numpy as np 
from typing import List, Optional

In [2]:
# Configurações de exibição
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 200)

%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.displaylimit = 100
%config SqlMagic.named_parameters = "enabled"
%config SqlMagic.autocommit = True

# Se preferir memória: 
%sql duckdb:///:memory:

Connecting to 'duckdb:///:memory:'

In [3]:
path = Path("C:/Users/silma/Projetos/vigimed/data/03_gold")
# Caminhos completos para o DuckDB (parâmetros nomeados não expandem expressões)
path_atc = str(path / 'dim_atc/dim_atc.parquet')
path_fat_medicamentos = str(path / 'fat_medicamentos/fat_medicamentos.parquet')
path_dim_notificacoes = str(path / 'dim_notificacoes/dim_notificacoes.parquet')
path_fat_reacoes = str(path / 'fat_reacoes/fat_reacoes.parquet')
path_dim_soc_llt = str(path / 'dim_soc_llt/dim_soc_llt.parquet')

In [4]:
%sql ROLLBACK;

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [Success]
Index: []

In [5]:
%%sql
DROP TABLE IF EXISTS dim_atc;
CREATE TABLE dim_atc AS
SELECT * FROM read_parquet(:path_atc);

DROP TABLE IF EXISTS fat_medicamentos;
CREATE TABLE fat_medicamentos AS
SELECT *
FROM read_parquet(:path_fat_medicamentos);

DROP TABLE IF EXISTS dim_notificacoes;
CREATE TABLE dim_notificacoes AS
SELECT *
FROM read_parquet(:path_dim_notificacoes);

DROP TABLE IF EXISTS fat_reacoes;
CREATE TABLE fat_reacoes AS
SELECT *
FROM read_parquet(:path_fat_reacoes);

DROP TABLE IF EXISTS dim_soc_llt;
CREATE TABLE dim_soc_llt AS
SELECT *
FROM read_parquet(:path_dim_soc_llt);

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [Success]
Index: []

# **5️⃣ Entendimento dos dados**

### dim_notificacoes

In [6]:
%%sql 
select * from dim_notificacoes limit 2

Running query in 'duckdb:///:memory:'

,UF,TIPO_ENTRADA_VIGIMED,RECEBIDO_DE,IDENTIFICACAO_NOTIFICACAO,DATA_INCLUSAO_SISTEMA,DATA_ULTIMA_ATUALIZACAO,DATA_NOTIFICACAO,TIPO_NOTIFICACAO,NOTIFICACAO_PARENT_CHILD,DATA_NASCIMENTO,IDADE_MOMENTO_REACAO,GRUPO_IDADE,IDADE_GESTACIONAL_MOMENTO_REACAO,SEXO,GESTANTE,LACTANTE,PESO_KG,ALTURA_CM,REACAO_EVENTO_ADVERSO_MEDDRA,GRAVE,GRAVIDADE,DESFECHO,DATA_INICIO_HORA,DATA_FINAL_HORA,DURACAO,RELACAO_MEDICAMENTO_EVENTO,NOME_MEDICAMENTO_WHODRUG,ACAO_ADOTADA,NOTIFICADOR,ATUALIZADO,HASH_BRONZE,UF_CHAVE,UF_VALOR,GRAVIDADE_CHAVE,GRAVIDADE_VALOR,TIPO_ENTRADA_VIGIMED_VALOR,TIPO_ENTRADA_VIGIMED_CHAVE,RECEBIDO_DE_VALOR,RECEBIDO_DE_CHAVE,TIPO_NOTIFICACAO_VALOR,TIPO_NOTIFICACAO_CHAVE,NOTIFICACAO_PARENT_CHILD_VALOR,NOTIFICACAO_PARENT_CHILD_CHAVE,GRUPO_IDADE_VALOR,GRUPO_IDADE_CHAVE,SEXO_VALOR,SEXO_CHAVE,GESTANTE_VALOR,GESTANTE_CHAVE,LACTANTE_VALOR,LACTANTE_CHAVE,GRAVE_VALOR,GRAVE_CHAVE,DESFECHO_VALOR,DESFECHO_CHAVE,RELACAO_MEDICAMENTO_EVENTO_VALOR,RELACAO_MEDICAMENTO_EVENTO_CHAVE,ACAO_ADOTADA_VALOR,ACAO_ADOTADA_CHAVE,NOTIFICADOR_VALOR,NOTIFICADOR_CHAVE,IDADE_MOMENTO_REACAO_TIPO_CHAVE,IDADE_MOMENTO_REACAO_TIPO_VALOR,IDADE_MOMENTO_REACAO_VALOR,DURACAO_TIPO_VALOR,DURACAO_TIPO_CHAVE,DURACAO_VALOR,IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_CHAVE,IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_VALOR,IDADE_GESTACIONAL_MOMENTO_REACAO_VALOR,HASH_SILVER
0,SP,EMPRESAS FARMACEUTICAS,EMPRESA FARMACEUTICA,BR-ANVISA-300212656,2023-09-28,2023-09-28,NaT,NOTIFICACAO ESPONTANEA,None,1990-01-31,30 ano,None,None,Feminino,Năo,Năo,68.0,165,Hemiparesia,Sim,OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO,RECUPERADO,2021-01-25,2021-02-06,12 dia,CONCOMITANTE,Tamisa,NAO APLICAVEL,MEDICO,2026-01-15,c540f6f2873cded948f9a6156d6a92cf9f59b7e110f84e...,25,SP,1,OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO,EMPRESAS FARMACEUTICAS,2,EMPRESA FARMACEUTICA,5,NOTIFICACAO ESPONTANEA,1,DESCONHECIDO,0,DESCONHECIDO,0,FEMININO,1,NĂO,2,NĂO,2,SIM,1,RECUPERADO,1,CONCOMITANTE,2,NAO APLICAVEL,2,MEDICO,4,1,ANO,30.0,DIA,4,12.0,0,DESCONHECIDO,NaN,3c04663c8c6a69bba2510ab19fa043d1d6670b81e42857...
1,SP,EMPRESAS FARMACEUTICAS,EMPRESA FARMACEUTICA,BR-ANVISA-300208322,2023-09-01,2023-09-01,NaT,NOTIFICACAO ESPONTANEA,None,NaT,None,None,None,Feminino,Năo,Năo,None,None,Cefaleia,Năo,OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO,DESCONHECIDO,2021-01-22,NaT,None,SUSPEITO,CoronaVac,NAO APLICAVEL,CONSUMIDOR OU OUTRO NAO PROFISSIONAL DE SAUDE,2026-01-15,1f6805d588f843fe6f27dc43ae2026701e8d0400f3a101...,25,SP,1,OUTRO EFEITO CLINICAMENTE SIGNIFICATIVO,EMPRESAS FARMACEUTICAS,2,EMPRESA FARMACEUTICA,5,NOTIFICACAO ESPONTANEA,1,DESCONHECIDO,0,DESCONHECIDO,0,FEMININO,1,NĂO,2,NĂO,2,NĂO,2,DESCONHECIDO,0,SUSPEITO,1,NAO APLICAVEL,2,CONSUMIDOR OU OUTRO NAO PROFISSIONAL DE SAUDE,2,0,DESCONHECIDO,NaN,DESCONHECIDO,0,NaN,0,DESCONHECIDO,NaN,716905c5a2cc460902e5682c94bd1379f674208b0c6ef5...

In [7]:
%%sql 
select IDENTIFICACAO_NOTIFICACAO,count(1) as qt
from dim_notificacoes 
group by 1
having qt > 1
limit 10

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [IDENTIFICACAO_NOTIFICACAO, qt]
Index: []

In [8]:
%%sql 
select * from dim_notificacoes 
where IDENTIFICACAO_NOTIFICACAO = 'BR-ANVISA-300171130'

Running query in 'duckdb:///:memory:'

,UF,TIPO_ENTRADA_VIGIMED,RECEBIDO_DE,IDENTIFICACAO_NOTIFICACAO,DATA_INCLUSAO_SISTEMA,DATA_ULTIMA_ATUALIZACAO,DATA_NOTIFICACAO,TIPO_NOTIFICACAO,NOTIFICACAO_PARENT_CHILD,DATA_NASCIMENTO,IDADE_MOMENTO_REACAO,GRUPO_IDADE,IDADE_GESTACIONAL_MOMENTO_REACAO,SEXO,GESTANTE,LACTANTE,PESO_KG,ALTURA_CM,REACAO_EVENTO_ADVERSO_MEDDRA,GRAVE,GRAVIDADE,DESFECHO,DATA_INICIO_HORA,DATA_FINAL_HORA,DURACAO,RELACAO_MEDICAMENTO_EVENTO,NOME_MEDICAMENTO_WHODRUG,ACAO_ADOTADA,NOTIFICADOR,ATUALIZADO,HASH_BRONZE,UF_CHAVE,UF_VALOR,GRAVIDADE_CHAVE,GRAVIDADE_VALOR,TIPO_ENTRADA_VIGIMED_VALOR,TIPO_ENTRADA_VIGIMED_CHAVE,RECEBIDO_DE_VALOR,RECEBIDO_DE_CHAVE,TIPO_NOTIFICACAO_VALOR,TIPO_NOTIFICACAO_CHAVE,NOTIFICACAO_PARENT_CHILD_VALOR,NOTIFICACAO_PARENT_CHILD_CHAVE,GRUPO_IDADE_VALOR,GRUPO_IDADE_CHAVE,SEXO_VALOR,SEXO_CHAVE,GESTANTE_VALOR,GESTANTE_CHAVE,LACTANTE_VALOR,LACTANTE_CHAVE,GRAVE_VALOR,GRAVE_CHAVE,DESFECHO_VALOR,DESFECHO_CHAVE,RELACAO_MEDICAMENTO_EVENTO_VALOR,RELACAO_MEDICAMENTO_EVENTO_CHAVE,ACAO_ADOTADA_VALOR,ACAO_ADOTADA_CHAVE,NOTIFICADOR_VALOR,NOTIFICADOR_CHAVE,IDADE_MOMENTO_REACAO_TIPO_CHAVE,IDADE_MOMENTO_REACAO_TIPO_VALOR,IDADE_MOMENTO_REACAO_VALOR,DURACAO_TIPO_VALOR,DURACAO_TIPO_CHAVE,DURACAO_VALOR,IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_CHAVE,IDADE_GESTACIONAL_MOMENTO_REACAO_TIPO_VALOR,IDADE_GESTACIONAL_MOMENTO_REACAO_VALOR,HASH_SILVER
0,SP,SERVICOS DE SAUDE,CENTRO REGIONAL DE FARMACOVIGILANCIA,BR-ANVISA-300171130,2023-01-10,2023-01-10,2023-01-10,NOTIFICACAO ESPONTANEA,None,NaT,58 ano,Adulto,None,Masculino,None,None,None,None,Prurido oral,Năo,None,RECUPERADO,2023-01-10,2023-01-10,None,SUSPEITO,Henetix,None,FARMACEUTICO,2026-01-15,0a98b73bf675dcce6bfbe0a7e08333c2bd6dad4a7ea962...,25,SP,0,DESCONHECIDO,SERVICOS DE SAUDE,1,CENTRO REGIONAL DE FARMACOVIGILANCIA,4,NOTIFICACAO ESPONTANEA,1,DESCONHECIDO,0,ADULTO,6,MASCULINO,2,DESCONHECIDO,0,DESCONHECIDO,0,NĂO,2,RECUPERADO,1,SUSPEITO,1,DESCONHECIDO,0,FARMACEUTICO,3,1,ANO,58.0,DESCONHECIDO,0,NaN,0,DESCONHECIDO,NaN,6c94238fcb1543d2c24c3036169c67658af91aa5c58794...

### fat_medicamentos

In [9]:
%%sql 
select * from fat_medicamentos 
where IDENTIFICACAO_NOTIFICACAO = 'BR-ANVISA-300171130'

Running query in 'duckdb:///:memory:'

,IDENTIFICACAO_NOTIFICACAO,RELACAO_MEDICAMENTO_EVENTO_VALOR,RELACAO_MEDICAMENTO_EVENTO_CHAVE,NOME_MEDICAMENTO_WHODRUG,PRINCIPIOS_ATIVOS_WHODRUG,ATC_CODE_LEVEL_4,DETENTOR_REGISTRO_CHAVE,CONCENTRACAO_TIPO_VALOR,CONCENTRACAO_TIPO_CHAVE,CONCENTRACAO_VALOR,CONCENTRACAO_VALOR_NUMERADOR,CONCENTRACAO_VALOR_DENOMINADOR,COMPONENTE_SUSPEITO_VALOR,COMPONENTE_SUSPEITO_CHAVE,ACAO_ADOTADA_VALOR,ACAO_ADOTADA_CHAVE,PROB_ADIC_ABUSO,PROB_ADIC_ERRO_DE_MEDICACAO,PROB_ADIC_EXPOSICAO_OCUPACIONAL,PROB_ADIC_FALSIFICACAO,PROB_ADIC_LOTES_TESTADOS_E_DENTRO_DAS_ESPECIFICACOES,PROB_ADIC_LOTES_TESTADOS_E_FORA_DAS_ESPECIFICACOES,PROB_ADIC_MEDICAMENTO_TOMADO_FORA_DA_DATA_DE_VALIDADE,PROB_ADIC_MEDICAMENTO_TOMADO_PELO_PAI,PROB_ADIC_SUPERDOSE,PROB_ADIC_USO_INCORRETO,PROB_ADIC_USO_OFF_LABEL_USO_SEM_REGISTRO,INDICACAO_MEDDRA_LLT_CHAVE,INDICACAO_RELATADA_NOTIFICADOR_INICIAL_LLT_CHAVE,DOSE_TIPO_VALOR,DOSE_TIPO_CHAVE,DOSE_VALOR,FREQUENCIA_DOSE,POSOLOGIA,DURACAO_TIPO_CHAVE,DURACAO_VALOR,INICIO_ADMINISTRACAO,FIM_ADMINISTRACAO,FORMA_FARMACEUTICA_CHAVE,VIA_ADMINISTRACAO_CHAVE,VIA_ADMINISTRACAO_MAE_PAI_CHAVE,NUMELO_LOTE,ATUALIZADO,HASH_BRONZE,HASH_SILVER,HASH_GOLD
0,BR-ANVISA-300171130,CONCOMITANTE,2,NOVALGINA,METAMIZOLE SODIUM,N02BB,0,DESCONHECIDO,0,NaN,NaN,NaN,DESCONHECIDO,0,DESCONHECIDO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MILLIGRAM (MG),1,1000.0,,None,0,NaN,2023-01-10,2023-01-10,14,6,5,None,2026-01-15,E8421CD05C810683B262026252DF85A8CB234025058ECE...,eb4d0c92502c072339426ef1c74c09d2bcc4e79034b55b...,d7c0da664d119ffd091652c43cc25448b20c13ddf821ca...
1,BR-ANVISA-300171130,CONCOMITANTE,2,BUSCOPAN,HYOSCINE BUTYLBROMIDE,A03BB,0,DESCONHECIDO,0,NaN,NaN,NaN,DESCONHECIDO,0,DESCONHECIDO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MILLIGRAM (MG),1,20.0,,None,0,NaN,2023-01-10,2023-01-10,14,6,5,None,2026-01-15,4AD3B12C405DB5047BDAF8B3178C11665390EA4407B788...,423f51a6d297a64fd485f8753ada0ff0f9d01daf3f38e4...,38e10a5bb1179c1cba8a6f503c91404bd62342c3a5b0eb...
2,BR-ANVISA-300171130,SUSPEITO,1,HENETIX,IOBITRIDOL,V08AB,0,DESCONHECIDO,0,NaN,NaN,NaN,DESCONHECIDO,0,DESCONHECIDO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,MILLILITRE (ML),2,106.0,,None,0,NaN,2023-01-10,2023-01-10,16,6,5,22WC366B,2026-01-15,C2F0D1941A6EB562A55B581E0F847EAB15244D0E276E9A...,b75c0cbe97ba4062e3e1adbe6c19ae965958e00c4aad07...,c08abb4a449234aa328b3f322d46b72daa575fc276c249...

### fat_reacoes

In [10]:
%%sql 
select * from fat_reacoes limit 2

Running query in 'duckdb:///:memory:'

,IDENTIFICACAO_NOTIFICACAO,HASH_BRONZE,HASH_SILVER,DATA_INICIO_HORA,DATA_FINAL_HORA,ATUALIZADO,LLT_CHAVE,GRAVE_CHAVE,DESFECHO_CHAVE,DURACAO_TIPO_CHAVE,DURACAO_VALOR,GRAVIDADE_RESULTADO_OBITO,GRAVIDADE_AMEACA_VIDA,GRAVIDADE_INCAPACIDADE,GRAVIDADE_HOSPITALIZACAO,GRAVIDADE_OUTRO_EFEITO,GRAVIDADE_ANOMALIA_CONGENITA
0,BR-ANVISA-300000004,e0102770fa7fe4e3e3f58fe5a3675e13fffd3dc4721c0b...,5e664ee6fcb8b1bf52f1a7aa7ef1853a166bf9cedfc2ff...,NaT,NaT,2025-11-17,4114,2,3,4,3.0,0,0,0,0,0,0
1,BR-ANVISA-300000005,21a5c47062a6ba174af4058e70e681ff97ba91db760676...,497e70fa95ec2b543e9cb065388b857d545c25059f7f69...,2018-11-22,2018-11-22,2025-11-17,9107,1,3,0,NaN,0,0,0,0,1,0

In [11]:
%%sql 
select * from fat_reacoes 
left join dim_soc_llt using (LLT_CHAVE)
where IDENTIFICACAO_NOTIFICACAO = 'BR-ANVISA-300171130'

Running query in 'duckdb:///:memory:'

,IDENTIFICACAO_NOTIFICACAO,HASH_BRONZE,HASH_SILVER,DATA_INICIO_HORA,DATA_FINAL_HORA,ATUALIZADO,LLT_CHAVE,GRAVE_CHAVE,DESFECHO_CHAVE,DURACAO_TIPO_CHAVE,DURACAO_VALOR,GRAVIDADE_RESULTADO_OBITO,GRAVIDADE_AMEACA_VIDA,GRAVIDADE_INCAPACIDADE,GRAVIDADE_HOSPITALIZACAO,GRAVIDADE_OUTRO_EFEITO,GRAVIDADE_ANOMALIA_CONGENITA,SOC_CHAVE,SOC_VALOR,HLGT,HLT,PT,REACAO_EVTO_ADVERSO_MEDDRA_LLT_VALOR
0,BR-ANVISA-300171130,bc80540a7cbefd2aca595577b9eefb0b73bc6ecac48230...,2249bcf07a8c777fa3000b360111166561c3169531d014...,2023-01-10,2023-01-10,2025-11-17,5029,2,3,0,NaN,0,0,0,0,0,0,14,Distúrbios gastrointestinais,Quadros clínicos de tecido mole oral,Estomatite e ulceração,Úlcera aftosa,Úlceras aftosas orais
1,BR-ANVISA-300171130,33cda90c040b2714862d636436c2f0105c1307a9b593d5...,5fd9d9ac6bbfa4ac4cc223114f7544e97b92b1d83ad75a...,2023-01-10,2023-01-10,2025-11-17,10541,2,3,0,NaN,0,0,0,0,0,0,13,"Distúrbios respiratórios, torácicos e do media...",Distúrbios brônquicos (excl. neoplasias),Quadros clínicos brônquicos NCO,Alteração brônquica,Alteração brônquica
2,BR-ANVISA-300171130,8d89edb6a4354411417b35144154c636741cce9c0dc40f...,22ed5404cb6f62dbd22e025be5e5b9b4b1a9dab16268e9...,2023-01-10,2023-01-10,2025-11-17,10898,2,3,0,NaN,0,0,0,0,0,0,13,"Distúrbios respiratórios, torácicos e do media...",Distúrbios respiratórios NCO,Distúrbios do trato respiratório NCO,Aspiração,Aspiração de vômito

### dim_soc_llt

In [12]:
%%sql 
select * from dim_soc_llt limit 2

Running query in 'duckdb:///:memory:'

   SOC_CHAVE               SOC_VALOR                            HLGT                                     HLT                  PT  LLT_CHAVE REACAO_EVTO_ADVERSO_MEDDRA_LLT_VALOR
0         26  Circunstâncias sociais  Fatores relacionados ao gênero  Circunstâncias relacionadas à gravidez         Amamentação          1                          Amamentação
1         26  Circunstâncias sociais  Fatores relacionados ao gênero                 Questões de sexualidade  Abstinência sexual          2                   Abstinência sexual

### 6.1 Aplicacao de regras de negócio

In [13]:
%%sql
DROP TABLE IF EXISTS fat_analytics;

CREATE TABLE fat_analytics AS
with fat_med as (
SELECT 
    fat_medicamentos.IDENTIFICACAO_NOTIFICACAO, 
    atc.ATC_CODE_LEVEL_4_LEVEL_NAME,
    (
        CASE 
            WHEN atc.ATC_CODE_LEVEL_4 IN ('L04AB', 'L04AA','L01FA', 'L04AC','L04AF') 
                THEN (
                    CASE 
                        /*Rituximab*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%rituximab%' THEN 'L01FA01_Rituximab'
                        /*Abatacept*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%abatacept%' THEN 'L04AA24_Abatacept'
                        /*Etanercept*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%etanercept%' THEN 'L04AB01_Etanercept'
                        /*Infliximab*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%infliximab%' THEN 'L04AB02_Infliximab'
                        /*Adalimumab*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%adalimumab%' THEN 'L04AB04_Adalimumab'
                        /*Certolizumab Pegol*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%certolizumab%' THEN 'L04AB05_Certolizumab Pegol'   
                        /*Golimumab*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%golimumab%' THEN 'L04AB06_Golimumab'
                        /*Tocilizumab*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%tocilizumab%' THEN 'L04AC07_Tocilizumab'
                        /*Baricitinib */ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%baricitinib%' THEN 'L04AF02_Baricitinib'
                        /*Upadacitinib*/ WHEN LOWER(PRINCIPIOS_ATIVOS_WHODRUG) LIKE '%upadacitinib%' THEN 'L04AF03_Upadacitinib' 
                        ELSE 'Outros'
                    END
                )
            ELSE 'Outros'
        END
    ) AS ATC_CODE_LEVEL_5_LEVEL_NAME
FROM fat_medicamentos
INNER JOIN dim_atc AS atc
    ON fat_medicamentos.ATC_CODE_LEVEL_4 = atc.ATC_CODE_LEVEL_4 
    AND atc.ATC_LEVEL = 4
)
,fat as (
select strftime(TRY_CAST(dim.DATA_INCLUSAO_SISTEMA AS DATE), '%Y-%m') as DATA_NOTIFICACAO
    ,dim.IDENTIFICACAO_NOTIFICACAO AS ID
    ,dim.UF
    ,dim.SEXO
    ,fat_med.ATC_CODE_LEVEL_4_LEVEL_NAME AS ATC_LEVEL_4
    ,fat_med.ATC_CODE_LEVEL_5_LEVEL_NAME AS ATC_LEVEL_5  
    ,dim_soc_llt.REACAO_EVTO_ADVERSO_MEDDRA_LLT_VALOR AS REACAO_LLT
    ,dim_soc_llt.PT AS REACAO_PT
from dim_notificacoes as dim
inner join fat_med using (IDENTIFICACAO_NOTIFICACAO)
inner join fat_reacoes using (IDENTIFICACAO_NOTIFICACAO)
left join dim_soc_llt on fat_reacoes.LLT_CHAVE = dim_soc_llt.LLT_CHAVE
)
 
-- Notificações com medicamentos específicos (não 'Outros')
select * from fat 
where ATC_LEVEL_5 <> 'Outros'

union all 

-- Notificações com 'Outros' SOMENTE se não tiverem medicamentos específicos que iremos estudar
select * from fat as a
where a.ATC_LEVEL_5 = 'Outros'
and a.ID NOT IN (
    SELECT b.ID
    FROM fat as b
    WHERE b.ATC_LEVEL_5 <> 'Outros' 
)

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [Success]
Index: []

### 6.2 Checagens

In [14]:
%%sql
select * from fat_analytics limit 5

Running query in 'duckdb:///:memory:'

,DATA_NOTIFICACAO,ID,UF,SEXO,ATC_LEVEL_4,ATC_LEVEL_5,REACAO_LLT,REACAO_PT
0,2025-05,BR-ANVISA-300333181,SP,Feminino,TUMOR NECROSIS FACTOR ALPHA (TNF-ALPHA) INHIBI...,L04AB02_Infliximab,Problema relacionado ao folheto do produto,Problema relacionado ao rótulo do produto
1,2025-05,BR-ANVISA-300333583,SP,Feminino,TUMOR NECROSIS FACTOR ALPHA (TNF-ALPHA) INHIBI...,L04AB06_Golimumab,Meningite tuberculosa,Meningite tuberculosa
2,2025-05,BR-ANVISA-300333583,SP,Feminino,TUMOR NECROSIS FACTOR ALPHA (TNF-ALPHA) INHIBI...,L04AB06_Golimumab,Bacteremia por Escherichia coli,Bacteremia por Escherichia
3,2025-05,BR-ANVISA-300333583,SP,Feminino,TUMOR NECROSIS FACTOR ALPHA (TNF-ALPHA) INHIBI...,L04AB06_Golimumab,Encefalite viral,Encefalite viral
4,2025-05,BR-ANVISA-300333120,SP,Feminino,TUMOR NECROSIS FACTOR ALPHA (TNF-ALPHA) INHIBI...,L04AB06_Golimumab,Complexo de inferioridade,Complexo de inferioridade

In [15]:
%%sql
select ATC_LEVEL_5,count(*) as qt,count(distinct ID) as qt_notificacoes from fat_analytics group by ATC_LEVEL_5

Running query in 'duckdb:///:memory:'

                   ATC_LEVEL_5       qt  qt_notificacoes
0   L04AB05_Certolizumab Pegol     5442             1177
1           L04AB01_Etanercept     3700              359
2           L04AB02_Infliximab    53915            10490
3          L04AF02_Baricitinib      738              205
4            L04AB06_Golimumab    12092             3723
5          L04AC07_Tocilizumab     3270              851
6            L04AA24_Abatacept      676              170
7            L01FA01_Rituximab     9912             2971
8           L04AB04_Adalimumab    11835             1519
9                       Outros  2306743           264340
10        L04AF03_Upadacitinib     7354             1023

In [16]:
%%sql
select id,count(1) from fat_analytics group by 1 having count(1) > 1 limit 2

Running query in 'duckdb:///:memory:'

                    ID  count(1)
0  BR-ANVISA-300214434        49
1  BR-ANVISA-300214529         6

In [17]:
%%sql 
select * from fat_analytics 
where id ='BR-ANVISA-300315256'

Running query in 'duckdb:///:memory:'

   DATA_NOTIFICACAO                   ID  UF      SEXO                                        ATC_LEVEL_4 ATC_LEVEL_5                             REACAO_LLT                              REACAO_PT
0           2025-01  BR-ANVISA-300315256  SP  Feminino                           ANTIVERTIGO PREPARATIONS      Outros  Complicação de intubação endotraqueal  Complicação de intubação endotraqueal
1           2025-01  BR-ANVISA-300315256  SP  Feminino                           ANTIVERTIGO PREPARATIONS      Outros                 Glomerulonefrite aguda                 Glomerulonefrite aguda
2           2025-01  BR-ANVISA-300315256  SP  Feminino                        DIHYDROPYRIDINE DERIVATIVES      Outros  Complicação de intubação endotraqueal  Complicação de intubação endotraqueal
3           2025-01  BR-ANVISA-300315256  SP  Feminino                        DIHYDROPYRIDINE DERIVATIVES      Outros                 Glomerulonefrite aguda                 Glomerulonefrite aguda
4           2025-01  BR-ANVISA-300315256  SP  Feminino                                SULFONAMIDES, PLAIN      Outros  Complicação de intubação endotraqueal  Complicação de intubação endotraqueal
5           2025-01  BR-ANVISA-300315256  SP  Feminino                                SULFONAMIDES, PLAIN      Outros                 Glomerulonefrite aguda                 Glomerulonefrite aguda
6           2025-01  BR-ANVISA-300315256  SP  Feminino     ANGIOTENSIN II RECEPTOR BLOCKERS (ARBS), PLAIN      Outros  Complicação de intubação endotraqueal  Complicação de intubação endotraqueal
7           2025-01  BR-ANVISA-300315256  SP  Feminino     ANGIOTENSIN II RECEPTOR BLOCKERS (ARBS), PLAIN      Outros                 Glomerulonefrite aguda                 Glomerulonefrite aguda
8           2025-01  BR-ANVISA-300315256  SP  Feminino                                         MACROLIDES      Outros  Complicação de intubação endotraqueal  Complicação de intubação endotraqueal
9           2025-01  BR-ANVISA-300315256  SP  Feminino                                         MACROLIDES      Outros                 Glomerulonefrite aguda                 Glomerulonefrite aguda
10          2025-01  BR-ANVISA-300315256  SP  Feminino  ADRENERGICS IN COMBINATION WITH ANTICHOLINERGI...      Outros  Complicação de intubação endotraqueal  Complicação de intubação endotraqueal
11          2025-01  BR-ANVISA-300315256  SP  Feminino  ADRENERGICS IN COMBINATION WITH ANTICHOLINERGI...      Outros                 Glomerulonefrite aguda                 Glomerulonefrite aguda
12          2025-01  BR-ANVISA-300315256  SP  Feminino  ADRENERGICS IN COMBINATION WITH ANTICHOLINERGI...      Outros  Complicação de intubação endotraqueal  Complicação de intubação endotraqueal
13          2025-01  BR-ANVISA-300315256  SP  Feminino  ADRENERGICS IN COMBINATION WITH ANTICHOLINERGI...      Outros                 Glomerulonefrite aguda                 Glomerulonefrite aguda

### 6.3 Persistindo a Base

In [18]:
%%sql df <<
select * from fat_analytics

Running query in 'duckdb:///:memory:'

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [19]:
df.to_parquet(path/'fat_analytical/fat_analytical.parquet', index=False)