In [22]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.displaylimit = 100
%config SqlMagic.named_parameters = "enabled"
%config SqlMagic.autocommit = True

# Banco em arquivo (persiste durante a sessão).
#%sql duckdb:///content/vigimed.duckdb
# Se preferir memória: 
%sql duckdb:///:memory:

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

## Atualizar a seção e abrir nova

In [23]:
%sql ROLLBACK;

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [Success]
Index: []

## Criar as tabela e fazer as consultas

In [24]:
%%sql
DROP TABLE IF EXISTS dim_soc;
CREATE TABLE dim_soc AS
SELECT * FROM read_parquet('/home/carolina/Área de trabalho/vigimed/data/03_gold/dim_soc/dim_soc.parquet');


DROP TABLE IF EXISTS fat_reacoes;
CREATE TABLE fat_reacoes AS
SELECT * FROM read_parquet('/home/carolina/Área de trabalho/vigimed/data/03_gold/fat_reacoes/fat_reacoes.parquet');

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [Success]
Index: []

In [9]:
%%sql
SELECT * 
FROM dim_soc
LIMIT 1;

Running query in 'duckdb:///:memory:'

,PK_SOC,SOC,HLGT,HLT,PT,PK_LLT,REACAO_EVTO_ADVERSO_MEDDRA_LLT
0,26,Circunstâncias sociais,Fatores relacionados ao gênero,Circunstâncias relacionadas à gravidez,Amamentação,1,Amamentação

In [10]:
%%sql
SELECT *
FROM fat_reacoes
LIMIT 1;

Running query in 'duckdb:///:memory:'

,IDENTIFICACAO_NOTIFICACAO,DATA_INICIO_HORA,DATA_FINAL_HORA,DURACAO,ATUALIZADO,PK_SOC,PK_LLT,GRAVE_TIPO,GRAVE_VALOR,DESFECHO_TIPO,DESFECHO_VALOR,DURACAO_VALOR,DURACAO_TIPO,GRAVIDADE_RESULTADO_OBITO,GRAVIDADE_AMEACA_VIDA,GRAVIDADE_INCAPACIDADE,GRAVIDADE_HOSPITALIZACAO,GRAVIDADE_OUTRO_EFEITO,GRAVIDADE_ANOMALIA_CONGENITA
0,BR-ANVISA-300000004,NaT,NaT,3 dia,2025-11-17,16,4114,Não,2,Recuperado/Resolvido,3,3.0,DIA(S),0,0,0,0,0,0

In [25]:
%%sql

DESCRIBE SELECT * FROM '/home/carolina/Área de trabalho/vigimed/data/03_gold/fat_reacoes/fat_reacoes.parquet';

Running query in 'duckdb:///:memory:'

Empty DataFrame
Columns: [Success]
Index: []

# OK - DATA_INICIO_HORA

In [11]:
%%sql
SELECT DATA_INICIO_HORA,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC
LIMIT 10;

Running query in 'duckdb:///:memory:'

  DATA_INICIO_HORA      qt
0              NaT  468181
1       2020-01-02    1317
2       2020-01-01     987
3       2022-01-02     952
4       2021-01-01     950
5       2021-01-02     916
6       2021-05-20     866
7       2021-06-02     864
8       2022-01-01     829
9       2023-01-01     816

# OK- DATA_FINAL_HORA

In [12]:
%%sql
SELECT DATA_FINAL_HORA,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC
LIMIT 10;

Running query in 'duckdb:///:memory:'

  DATA_FINAL_HORA      qt
0             NaT  626402
1      2019-04-23     551
2      2021-06-05     455
3      2021-06-04     392
4      2021-06-06     385
5      2021-06-03     374
6      2021-05-20     354
7      2021-05-21     323
8      2021-05-22     322
9      2021-05-06     321

# OK- DURACAO
Ajuste sendo feito na fat_medicamentos

In [13]:
%%sql
SELECT DURACAO,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC
LIMIT 10;

Running query in 'duckdb:///:memory:'

        DURACAO      qt
0  desconhecido  688151
1         1 dia   27059
2         2 dia   10017
3         3 dia    6650
4        1 hora    6314
5     30 minuto    5865
6         4 dia    4278
7         5 dia    3707
8         0 dia    3349
9        2 hora    3112

# GRAVE

In [17]:
%%sql
SELECT GRAVE_TIPO, GRAVE_VALOR,count(*) as qt 
FROM fat_reacoes
GROUP BY 1,2  
ORDER BY qt DESC
LIMIT 10;

Running query in 'duckdb:///:memory:'

     GRAVE_TIPO  GRAVE_VALOR      qt
0           Não            2  374682
1           Sim            1  268114
2  Desconhecido            0  173081

# DESFECHO

In [18]:
%%sql
SELECT DESFECHO_TIPO, DESFECHO_VALOR ,count(*) as qt 
FROM fat_reacoes
GROUP BY 1,2 
ORDER BY qt DESC
LIMIT 10;

Running query in 'duckdb:///:memory:'

                               DESFECHO_TIPO  DESFECHO_VALOR      qt
0                               Desconhecido               0  362166
1                       Recuperado/Resolvido               3  278670
2  Não Recuperado/Não Resolvido/Em andamento               1   85241
3                  Em recuperação/Resolvendo               2   66908
4                                Fatal/Óbito               4   18581
5          Recuperado/Resolvido com sequelas               5    4311

# OK- ATUALIZADO

In [ ]:
%%sql
SELECT ATUALIZADO,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC

Running query in 'duckdb:///:memory:'

   ATUALIZADO      qt
0  2025-11-17  815877

# DURACAO_VALOR

In [ ]:
%%sql
SELECT DURACAO_VALOR,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC
LIMIT 10;

Running query in 'duckdb:///:memory:'

   DURACAO_VALOR      qt
0            NaN  688275
1            1.0   37128
2            2.0   15479
3            3.0    9917
4           30.0    6422
5            5.0    6190
6            4.0    6146
7           10.0    4270
8            6.0    3670
9            0.0    3481

In [ ]:
%%sql
SELECT *
FROM fat_reacoes
WHERE DURACAO_VALOR ='1.50'
LIMIT 10;

Running query in 'duckdb:///:memory:'

,IDENTIFICACAO_NOTIFICACAO,PK_SOC,PK_LLT,DATA_INICIO_HORA,DATA_FINAL_HORA,DURACAO,GRAVE,DESFECHO,ATUALIZADO,DURACAO_VALOR,DURACAO_TIPO,GRAVIDADE_RESULTADO_OBITO,GRAVIDADE_AMEACA_VIDA,GRAVIDADE_INCAPACIDADE,GRAVIDADE_HOSPITALIZACAO,GRAVIDADE_OUTRO_EFEITO,GRAVIDADE_ANOMALIA_CONGENITA
0,BR-ANVISA-300036565,14,5693,NaT,NaT,1.5 hora,2,3,2025-11-17,1.5,hora,0,0,0,0,0,0
1,BR-ANVISA-300054316,11,260,NaT,NaT,1.5 hora,2,3,2025-11-17,1.5,hora,0,0,0,0,0,0
2,BR-ANVISA-300069861,16,4092,2021-06-30,2021-06-30,1.5 hora,2,3,2025-11-17,1.5,hora,0,0,0,0,0,0
3,BR-ANVISA-300087980,22,6126,2021-01-31,2021-02-12,1.5 semana,1,5,2025-11-17,1.5,semana,0,0,0,0,1,0
4,BR-ANVISA-300087980,13,10887,2021-01-31,2021-02-12,1.5 semana,1,5,2025-11-17,1.5,semana,0,0,0,0,1,0
5,BR-ANVISA-300087980,22,6526,2021-01-31,2021-02-12,1.5 semana,1,5,2025-11-17,1.5,semana,0,0,0,0,1,0
6,BR-ANVISA-300094307,3,3278,2021-10-13,2021-10-14,1.5 dia,2,2,2025-11-17,1.5,dia,0,0,0,0,0,0
7,BR-ANVISA-300095044,17,8206,2021-10-10,NaT,1.5 semana,1,1,2025-11-17,1.5,semana,0,0,0,0,1,0
8,BR-ANVISA-300106904,1,12547,2021-11-07,NaT,1.5 mês,1,2,2025-11-17,1.5,mês,0,0,0,0,1,0
9,BR-ANVISA-300108707,17,8231,NaT,NaT,1.5 hora,2,3,2025-11-17,1.5,hora,0,0,0,0,0,0

# DURACAO_TIPO

In [26]:
%%sql
SELECT DURACAO_TIPO,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC

Running query in 'duckdb:///:memory:'

   DURACAO_TIPO      qt
0  desconhecido  688175
1        DIA(S)   76020
2     MINUTO(S)   24232
3       HORA(S)   17868
4       MES(ES)    5644
5     SEMANA(S)    2259
6        ANO(S)    1313
7    SEGUNDO(S)     353
8     DECADA(S)      13

# GRAVIDADE_RESULTADO_OBITO

In [ ]:
%%sql
SELECT GRAVIDADE_RESULTADO_OBITO,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC

Running query in 'duckdb:///:memory:'

   GRAVIDADE_RESULTADO_OBITO      qt
0                          0  797247
1                          1   18630

# GRAVIDADE_AMEACA_VIDA

In [ ]:
%%sql
SELECT GRAVIDADE_AMEACA_VIDA,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC

Running query in 'duckdb:///:memory:'

   GRAVIDADE_AMEACA_VIDA      qt
0                      0  794831
1                      1   21046

# GRAVIDADE_INCAPACIDADE

In [ ]:
%%sql
SELECT GRAVIDADE_INCAPACIDADE,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC

Running query in 'duckdb:///:memory:'

   GRAVIDADE_INCAPACIDADE      qt
0                       0  802351
1                       1   13526

# GRAVIDADE_HOSPITALIZACAO

In [ ]:
%%sql
SELECT GRAVIDADE_HOSPITALIZACAO,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC

Running query in 'duckdb:///:memory:'

   GRAVIDADE_HOSPITALIZACAO      qt
0                         0  729438
1                         1   86439

# GRAVIDADE_OUTRO_EFEITO

In [ ]:
%%sql
SELECT GRAVIDADE_OUTRO_EFEITO,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC

Running query in 'duckdb:///:memory:'

   GRAVIDADE_OUTRO_EFEITO      qt
0                       0  641920
1                       1  173957

# GRAVIDADE_ANOMALIA_CONGENITA

In [ ]:
%%sql
SELECT GRAVIDADE_ANOMALIA_CONGENITA,count(*) as qt 
FROM fat_reacoes
GROUP BY 1  
ORDER BY qt DESC

Running query in 'duckdb:///:memory:'

   GRAVIDADE_ANOMALIA_CONGENITA      qt
0                             0  815429
1                             1     448

In [27]:
import pandas as pd

caminho_arquivo = '/home/carolina/Área de trabalho/vigimed/data/03_gold/fat_reacoes/fat_reacoes.parquet'

# Use a função read_parquet()
df = pd.read_parquet(caminho_arquivo)

# O DataFrame 'df' agora está carregado.
print("--- Primeiras linhas do DataFrame (df) ---")
print(df.head())

--- Primeiras linhas do DataFrame (df) ---
  IDENTIFICACAO_NOTIFICACAO DATA_INICIO_HORA DATA_FINAL_HORA       DURACAO  \
0       BR-ANVISA-300000004              NaT             NaT         3 dia
1       BR-ANVISA-300000005       2018-11-22      2018-11-22  desconhecido
2       BR-ANVISA-300000007       2018-11-15             NaT         2 dia
3       BR-ANVISA-300000008       2018-10-25             NaT         5 dia
4       BR-ANVISA-300000010              NaT             NaT  desconhecido

   ATUALIZADO  PK_SOC  PK_LLT GRAVE_TIPO  GRAVE_VALOR         DESFECHO_TIPO  \
0  2025-11-17      16    4114        Não            2  Recuperado/Resolvido
1  2025-11-17       9    9107        Sim            1  Recuperado/Resolvido
2  2025-11-17      16    3903        Sim            1  Recuperado/Resolvido
3  2025-11-17      12   11411        Sim            1  Recuperado/Resolvido
4  2025-11-17       8    1994        Sim            1  Recuperado/Resolvido

   DESFECHO_VALOR  DURACAO_VALOR  DURACAO_TIPO  GRAVIDADE_RESULTADO_OBITO  \
0               3            3.0        DIA(S)                          0
1               3            NaN  desconhecido                          0
2               3            2.0        DIA(S)                          0
3               3            5.0        DIA(S)                          0
4               3            NaN  desconhecido                          0

   GRAVIDADE_AMEACA_VIDA  GRAVIDADE_INCAPACIDADE  GRAVIDADE_HOSPITALIZACAO  \
0                      0                       0                         0
1                      0                       0                         0
2                      0                       0                         0
3                      0                       0                         0
4                      0                       0                         1

   GRAVIDADE_OUTRO_EFEITO  GRAVIDADE_ANOMALIA_CONGENITA
0                       0                             0
1                       1                             0
2                       1                             0
3                       1                             0
4                       0                             0

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 815877 entries, 0 to 815876
Data columns (total 19 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   IDENTIFICACAO_NOTIFICACAO     815877 non-null  object
 1   DATA_INICIO_HORA              347696 non-null  datetime64[ns]
 2   DATA_FINAL_HORA               189475 non-null  datetime64[ns]
 3   DURACAO                       815877 non-null  object
 4   ATUALIZADO                    815877 non-null  object
 5   PK_SOC                        770393 non-null  Int64
 6   PK_LLT                        815877 non-null  int64
 7   GRAVE_TIPO                    815877 non-null  object
 8   GRAVE_VALOR                   815877 non-null  Int64
 9   DESFECHO_TIPO                 815877 non-null  object
 10  DESFECHO_VALOR                815877 non-null  Int64
 11  DURACAO_VALOR                 127602 non-null  float64
 12  DURACAO_TIPO                  815877 non-null  object
 13  GRAVIDADE_RESULTADO_OBITO     815877 non-null  int8
 14  GRAVIDADE_AMEACA_VIDA         815877 non-null  int8
 15  GRAVIDADE_INCAPACIDADE        815877 non-null  int8
 16  GRAVIDADE_HOSPITALIZACAO      815877 non-null  int8
 17  GRAVIDADE_OUTRO_EFEITO        815877 non-null  int8
 18  GRAVIDADE_ANOMALIA_CONGENITA  815877 non-null  int8
dtypes: Int64(3), datetime64[ns](2), float64(1), int64(1), int8(6), object(6)
memory usage: 87.9+ MB